DFO-Ocean-Navigator/Ocean-Data-Map-Project

oceannavigator/frontend/src/components/PlotImage.jsx

Made changes so that it takes 2 queries to trigger the failed image to be loaded. This makes it less likely to trigger the race condition that was causing the Faile image (sad computer png) to render over the plot after it loads properly. This is a poor fix as the error is not always triggered when it should be.

Reduced the probability of the Failed image being triggered

---

data/fvcom.py
data/nemo.py
oceannavigator/nearest_grid_point.py
plotting/grid.py

In my drift verification work, I profiled the Python code to check for performance bottlenecks. In the function where the k-d tree is set up (which is code borrowed from Ocean Navigator), approximately 80% of the time was spent in constructing the `triples` array. The offending statement was:
```
triples = np.array(list(zip(np.ravel(clat * clon),
np.ravel(clat * slon),
np.ravel(slat))))
```
I rewrote that one statement as:
```
triples = np.array([np.ravel(clat * clon), np.ravel(clat * slon),
np.ravel(slat)]).transpose()
```
Some quick tests showed that this resulted in a reduction of the time to construct the `triples` array by more than a factor of 40.

Improve performance of array creation used in finding indices.

---

plotting/map.py

I changed the `depth_value` that is read by the `np.where`  because under some cases it was getting a multidimensional array filled with all the same values and sometimes it would just get one value (not an array). The call would never be called on the bottom values so I don't know why it was written the way it was. the `np.where` call worked fine when it was a single value but crashed if it was the array. so now it will only ever call it on the single value. This seems to produce valid results but a second look to make sure this is a fine thing to do would be appreciated. 
https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/blob/e920105f38984005e428b710e7fcba388169f298/plotting/map.py#L400
It does fix isses #337 & #347.

CSV bug fix #337 & #347.

---

data/netcdf_data.py

* Described here: https://github.com/pydata/xarray/issues/2822#issuecomment-475487497
* Until we get our conda environment fixed this will have to do.

Workaround for subset failure

---

data/netcdf_data.py

- Something with Geoff's code changes the list `variable_list` to not include the lat lon variables (I've no idea).
- This PR makes the subset function search through the superset of variable_list for the lat lon variables.

Lat / Lon variable fix for subsetting 

---

oceannavigator/frontend/src/components/Permalink.jsx

Our permalinks can get a little...large, so here's a workaround:

Make link customization panel expanded by default

---

config/conda/environment.yml

Updates `cftime` to version `1.0.1` from `1.0.0` to fix drifter plots.
Since the environment update drifter plots haven't been working.

Drifter plot fix (environment update)

---

routes/api_v1_0.py
tests/test_api_v_1_0.py

* Remove logic for per-variable quantums.
* Fix test failure for quantum endpoint.
`tests/test_api_v_1_0.py` passes so I'm considering this good to go.

Simplify quantum API endpoint

---

data/__init__.py
data/netcdf_data.py
data/utils.py
routes/api_v1_0.py
tests/test_api_v_1_0.py
tests/test_data_utils.py

* Crashed when timestamps for a calculated variable were requested.
* The key of the calculated variables was used in the timestamps sql query. Since the indexing tool only considers variables inside netcdf files, the resulting list was empty.
* The API now checks against the `DatasetConfig.calculated_variables` property, and performs additional parsing of the calculated variable's equation to extract the data variables, and then performs the original sql query.
* Added a new helper function in the `data.utils` package called `get_data_vars_from_equation` to prevent code duplication in `__init__.py`.
`tests/test_data_utils.py` and `tests/test_api_v_1_0.py` pass so I'm considering this good to go.

Fix crash in timestamps api endpoint

---

plotting/map.py

Fixes #496
Tested on my local machine for GIOPS Daily:
The colour scale is messed up, and there's no way to change it, but that's a separate issue.

Fix crash when in compare mode for Area plots

---

oceannavigator/datasetconfig.json
tests/test_data_utils.py

Resolves #479 
data/calculated_parser.functions defines a sound speed function as:
sspeed(depth, latitude, temperature, salinity)
in oceannavigator/datasetconfig.json we set an equation using sspeed as
sspeed(depth, latitude, salinity, temperature)
I've corrected the calls in oceannavigator/datasetconfig.json
I also corrected the call order in test/test_data_utils.py but I don't think it was necessary. 
Hopefully this fixes the bug where sound profiles generated from the Sound Speed Profile tab are different from sounds profiles generated from the Profile tab (latter is incorrect). Also, the maps of sounds speed will be corrected.

corrected bug in temperature/salinity reversal in calls to sspeed calculation

---

data/calculated_parser/functions.py
oceannavigator/datasetconfig.json
plotting/point.py
plotting/scale.py
plotting/stick.py

* Creates a new `magnitude` function for the calculation layer. It computes the element-wise magnitude of two matrices (of equal shape). The magnitude function basically does the following:
https://en.wikipedia.org/wiki/Hadamard_product_(matrices)
* This will allow us to clean up the `if len(variables) == 2` checks throughout our code. Also, will be no need for comma-separated variable keys (i.e. instead of `vomecrty,vozocrtx`, we can have `magwatervel`).
* This PR enables the Water Velocity magnitude calculation for GIOPS Daily and Monthly only. If all goes well, RIOPS will be enabled shortly. Sea ice velocity will be enabled later too.
* OF NOTE: at this time, in order to computer the magnitude of two calculated variables, the equations of said variables must be used as arguments to the …

Implement `magnitude` calculation function

---

data/data.py
data/netcdf_data.py
oceannavigator/frontend/src/components/PointWindow.jsx
plotting/timeseries.py

The sqlite backend migration changed how datasets are "opened", so most of the plotting classes were broken. The initial merge had fixes for most plot types except for virtual mooring and stick plots.
I've also fixed the timeseries functions in data.py so that we don't construct a range from the timestamp values, and instead have a list of [start, end] from where we find the corresponding indices in the dataset's time dimension.
Given the small amount of test data I have, the results are identical to the same time range on the public site. I'll consider this good to go.

Fix virtual mooring

---

data/calculated_parser/functions.py
oceannavigator/datasetconfig.json
tests/test_functions.py

Adds Unittests for the point functions for each of the sound speed calculations.
This means that it's testing that the correct value is being selected from the profile, but is not testing the looping through each profile.
This also adds sscp which is the possibility of a secondary sound channel at that point, and is either 0 if their isn't a possibility, or 1 if their is a possibility.
(This also has tests)

Add Unittests for Sound Channel Calculations and SSCP

---

plotting/timeseries.py

* The time indexing was wrong. Not sure how I missed that.
Resulting plot:

Fix virtual mooring crash

---

oceannavigator/frontend/src/components/AreaWindow.jsx

Fixed the area map colour selection. The selection box was not previously showing.
There was a comma instead of a period in the colourmaps request.

fixed colourmap url

---

data/__init__.py
data/mercator.py
data/sqlite_database.py
tests/test_sqlite_database.py

This issue came up when datasets using the Mercator grid were being requested in the Navigator. The following error was occuring: 
```sh
File "/home/nabil/Ocean-Data-Map-Project/data/nemo.py", line 78, in __bounding_box
minx, maxx = fix_limits(x, latvar.shape[1])
IndexError: tuple index out of range
```
The error being thrown from `nemo.py` was the obvious giveaway. Why was a mercator-gridded dataset using a nemo file? Turns out the bounding box function had nothing to do with this. The problem had to be in the `open_dataset` logic, so that's where the fixes are.
Instead of looking at the dataset variables like we used to be, we now look at the dimensions since they're more consistent across datasets.
The primary observation was that Mercator and Nemo dimension names are always different …

Fix loading of Mercator datasets

---

oceannavigator/frontend/src/stylesheets/components/_Map.scss

Resolves #579 
Fixes the odd page scrolling when changing time.
Changed inline block to inline. Because it is technically a horizontal piece flipped sideways inline block was preserving the width or something.

Ui scroll fix

---

data/mercator.py
data/nemo.py

When sending API requests for depth-related plots with a variable that has no depth dimension, a rather cryptic `ValueError` is thrown in debug mode. On production we get generic 500 errors. The back end now does a quick check if the shape of the requested variable matches that of a 3D + time (4D), if the check fails, the api exception is thrown immediately so the user gets a super fast slap on the wrist. 
Note: There is some obvious code duplication that'll be addressed in the New Year.
* Throws an `APIError` if the requested dataset has no depth which gets passed through the API.
API result:
Example banner displayed:
Tested against other datasets with depth dimensions and no change in behaviour occurs as intended.

Add check for depth dimension in get_profile

---

oceannavigator/frontend/src/components/LayerSelection.jsx

The text was too large and causing the scrollbar to appear

Makes the Cookie disclaimer smaller

---

data/__init__.py
tests/test_data_open_dataset.py
utils/decorators.py

Simply re-implementing the LRU cache that was present before the sqlite backend refactor in the `open_dataset` function. The idea is to reduce the overhead of opening the same dataset in quick succession by caching the last 16 used dataset objects.
This implementation is more complicated than the original one because of the presence of un-hashable types (`list`) in the `**kwargs` of `open_dataset` (read the docstring). The json serialisation recursively handles that. There obviously is a performance cost, but it should be less than going through all the file opening logic (i.e. disk reads).
I've also added a helper decorator `freeze_args` that will non-recursively convert a function's arguments to a `frozendict`, which allows the use of python's built-in `@lru_cache` decorator.
The …

Implement LRU cache for open_dataset

---

tests/test_data_functions.py

The calculated functions in the `data/calculated_parser` folder at present have no tests. This gets the ball rolling with tests for `min`, `max`, and `magnitude`.
Simplest approach. I also use the numpy test helpers: https://docs.scipy.org/doc/numpy/reference/routines.testing.html
I've defined a variable called `relative_tolerance` which controls how many decimal places are checked for floating-point equality. It's set to `1e-3` or 3 decimal places which should be sufficient for our needs. 
I feel this should be a "global" constant somewhere for behavioral consistency.
Not needed here.
```sh
```

Add test class for calculated functions

---

data/calculated_parser/parser.py
tests/test_calculated_parser.py

parser.py:
When a syntax error occurs in an equation string, part of the `t` parameter is attempted to be assigned to `None`. Unfortunately that results in another unrelated Python exception that confuses the caller. Instead we explicitly raise a `SyntaxError` exception, along with some useful debug info in the message (see below).
I threw in a new test case to check for the new raising behavior, along with some pylint formatting.
> In preparation for bringing back the derived variables.
Easiest way.
PLY is built around error feedback so I opted to pass along a more sane exception message
to the console:
```
SyntaxError: Syntax error in equation: atan2(0,)...LexToken(RPAREN,')',1,8)
```
The new test is only hitting the built-in math functions since they don't need to be mocked. To enhance …

Raise SyntaxError when p_error is called

---

data/calculated.py
oceannavigator/datasetconfig.json
tests/test_calculated_data.py

When the calculation layer was implemented, it only considered calculated variables to have the same dimensions as the underlying variables. So 3D calculated variables were only constructed from 3D underlying variables, and the same goes with 2D stuff. The `CalculatedArray` simply looked into the dimensions of the underlying variables and copied the maximum `.shape` values. This is just fine given the above consideration.
The issues arises when we consider 2D calculated variables with 3D underlying variables (e.g. Deep Sound Channel). We cannot simply copy the shapes of the 3D variables since we'll be pulling in depth, when there shouldn't be one. To work around this, I simply made the user-defined `dims` attribute in the dataset config file a requirement for all calculated variables. …

Change shape of CalculatedArray to consider user-defined dims

---

data/calculated_parser/functions.py
oceannavigator/datasetconfig.json
plotting/colormap.py

Add Density, Heat Capacity, and Adiabatic Temperature Gradient to GIOPS/RIOPS 3D Polar Stereographic datasets.
We simply expose more functions in the `seawater` package to the calculation layer.
Easiest way.
Deleted the generic "gradient" colour map since it didn't necessarily well represent gradient plots. 
```sh
```

Add Density, Heat Capacity, Temp Gradient variables

---

data/data.py

See https://docs.python.org/3.6/library/abc.html#abc.abstractproperty
> Deprecated since version 3.3: It is now possible to use property, ...
> with abstractmethod(), making this decorator redundant.
Keeping code up to date is A Good Thing™.
Python 3.2 that required `@abc.abtractproperty` was EOL-ed in March 2016.
Noticed this as I started to work on ioc/factory refactoring.
N/A
```sh
```

Fix deprecated uses of @abc.abstractproperty

---

oceannavigator/datasetconfig.json

We actually had these port models available over the summer but removed them with the back-end refactor
Nope.
```sh
```

Add port of St John and Bay of Fundy datasets

---

utils/misc.py

`misc.py` has been missing this import for a while and has been messing with the drifters. This PR replaces the import.
It seemed most effective.
The new import on line 19.
None
```sh
```

Added missing import

---

data/sqlite_database.py

Just adds DISTINCT qualifier to SELECT
For some forecast datasets, the sql database driver returns duplicate timestamps from the database. These end up being passed up to the front-end via the API and causes end-user confusion. As a quick fix, I've opted to simply use the `DISTINCT` qualifier on the `SELECT` statement to quickly filter out duplicates. When time permits, we can do a proper investigation.
Simplest method.
Nope
n/a
```sh
```

Fix duplicate timestamps returned from database

---

data/calculated.py
data/calculated_parser/lexer.py
data/calculated_parser/parser.py
tests/test_calculated_data.py
tests/test_calculated_parser.py

The requested acoustic calculations required the "compression" of 3D data variables into 2D (i.e. full-depth temperature + full-depth salinity would yield a 2D deep sound channel product). The parser grammar didn't support this kind of slicing so we needed to add new tokens ("[" and "]"). 
To request a variable be sliced with full-depth, use the following syntax in the dataset config: `[ my-variable-key ]`. The square brackets tell the parser to grab the full depth dimension when slicing the requested lat/lon coords.
Simplest way I could think of to minimize the amount of code changed, while keeping present functionality. The square brackets were borrowed from math, where they refer to inclusive ranges; where we want the full depth range.
The `dims` attribute for calculated variables in …

Extend calculation layer to support full-depth slicing

---

data/calculated_parser/functions.py
oceannavigator/datasetconfig.json
plotting/colormap.py
tests/test_data_functions.py

tldr: Someone wanted sound channel calculations, and so we deliver.
Available in:
* GIOPS Forecast 3D (Lat/Lon)
* GIOPS Forecast 3D PS
* RIOPS Forecast 3D PS
Deep Sound Channel is defined as the depth where the minimum sound speed occurs in a given vertical column.
I also added a basic test for the new `deepsoundchannel` function.
Fastest performing implementation since it's vectorized.
Not really. Vectorized code sometimes isn't the most intuitive to understand so I've added some comments to hopefully clarify things.
Fixed a crash when calculating pressure with GIOPS Forecast 3D (Lat/Lon) so speed of sound is now available there too.
```sh
python -m unittest `find tests -name "*.py" | grep …
```

Add Deep Sound Channel calculated variable

---

oceannavigator/datasetconfig.json

@dwayne-hart found some more datasets on Copernicus and we've never displayed an Arctic projection before so this is a novel addition.
Nope.
Global projection
Arctic Projection
```sh
```

Add MyOcean Arctic Datasets

---

oceannavigator/dataset_config.py
tests/test_dataset_config.py

Once upon a time we constructed "vector variables" using two variables keys connected by a comma (e.g. "vomecrty,vozocrtx") to indicate a magnitude calculation. Now that we have a magnitude function defined in the calculation layer, this composite stuff can be removed. There are lots of places in the code where we do checks for composite keys, however the changes here specifically update the `DatasetConfig` class to check for `mag` substring in the dataset key instead of a comma.
This should fix the Navigator being unable to display vector variables in the Transect window.
Most flexible way
NOTE: This will result in duplicate magnitude variables being displayed in the front-end because of some deprecated logic in the api. That will be removed in a new PR.
n/a
_Hint_ To run all python unit …

Fix vector_variables property in DatasetConfig class.

---

oceannavigator/frontend/src/components/AreaWindow.jsx
oceannavigator/frontend/src/components/DatasetSelector.jsx
oceannavigator/frontend/src/components/PointWindow.jsx
routes/api_v1_0.py
tests/test_api_v_1_0.py

Extension of #647 where I removed the need for the `vectors` option in the API since we calculate the magnitude properly through the calculation layer.
This resolves the duplicate magnitude variables in the front-end introduced by #647 
Did a search of the code and removed all references of `vectors`.
Nope
n/a
```sh
```

Deprecate vectors api argument

---

oceannavigator/datasetconfig.json

Add the 10-day forecasts.
Disable arctic datasets to reduce the dropdown scroll bar bloat.
It's the only way,
nope
```sh
```

Add 10-day forecasts

---

data/mercator.py

Resolves #653 
Looked back in the git blame and the last commit related to this code was by me two years ago. Seems like this code path hasn't been used for a very long time. Doing a search for `self.__latsort` and `self.__lonsort` yielded these two locations.
It's the only way
nope
n/a
```sh
```

Remove unused attributes in mercator.py

---

data/netcdf_data.py

Some datasets have floating-point values in their time dimensions, even though the sqlite databases store them as integers (see below for reasoning) which causes the `timestamp_to_time_index` method to not find a corresponding time index since int -> float comparisons don't work.
I've opted to simple bring forward the database logic and do a quick cast to integer in order to account for this case.
Least painful way.
It's worth emphasizing that it's ok to cast these float values to integers since our datasets do not require millisecond-or-higher time resolution. All datasets are either "hours since" or "seconds since...". The sqlite databases also make this assumption, hence the timestamp column is marked as INTEGER.
This method works for now, however if we get a dataset down the road …

Cast time dim values to int when calculating corresponding time index

---

data/calculated_parser/functions.py
oceannavigator/datasetconfig.json
plotting/colormap.py

Variables available on all GIOPS and RIOPS datasets.
It's the only way
Nope
```sh
```

Add Nitrogen and Oxygen Solubility calculated variables

---

oceannavigator/frontend/src/components/TimePicker.jsx

The hour selector in the front-end was automatically converting UTC to the client browsers time zone. This caused some confusion since the datasets we display are in UTC. Also, the time label says UTC.
Tweak `Timepicker.jsx` to format the hours/minutes in UTC and not the client time zone.
Two line change.
cc @nsoontie 
The signature for `dateFormat` is:
```ts
dateFormat(
date?: Date | string | number,
mask?: string,
utc?: boolean,
gmt?: boolean
)
```
```sh
```

Front-end: display hours in UTC

---

oceannavigator/frontend/src/components/Map.jsx
routes/api_v1_0.py

A new set of Mapbox tiles were created to increase the max zoom level. This PR changes some of the boundaries to allow users to zoom in further and use the new tiles.
only way
Halifax harbor at second to highest zoom level
```sh
```

Increase Max Zoom

---

data/calculated_parser/functions.py
oceannavigator/datasetconfig.json
tests/test_data_functions.py

New variable has been added to all giops/riops 3D datasets.
Vectorized and as memory-efficient as I can make it.
Nope.
```sh
```

Implement sonic layer depth calculated variable

---

launch-web-service.sh
runserver.sh

Need to come up with a way such that researchers are able to launch their own Navigator instance. The script will check to see if a network port is free. If it is not it increments by one and checks again. If the port is not  in use it will proceed with launching the Navigator on the available port.
In order to allow multiple users to be able to launch their own instance or possibly multiple instances of the Navigator on various machines.
There is no exponential backoff. The script will just keep going from 5000 by 1 until a free port is found. Also, the user is given the URL which is the <IP Address>:<PORT> where the instance is running.
N/A

GPSC modifications

---

runserver.sh

Launch as many gunicorn processes as their are processors. The timeout was increased for both the silent works terminated and restated. And again for the graceful restart of workers.
Previously we set the number of gunicorn processes to some value. Depending on the instance resources there were either to many or to few gunicorn services running. This will launch the number of gunicorn processes as their are processors. 
Also, the timeout values were increased from 90s to 300s. Depending on what datasets were selected and if there was a large time range requested. The stalled gunicorn processes were terminated.
- [ N/A] I ran unit tests.

Update to the runserver.sh script

---

data/fvcom.py
data/mercator.py
data/nearest_grid_point.py
data/nemo.py
data/netcdf_data.py
plotting/drifter.py
plotting/hovmoller.py
plotting/observation.py
plotting/plotter.py
plotting/scriptGenerator.py
plotting/stats.py
plotting/timeseries.py
routes/api_v1_0.py
tests/disabled/test_fvcom.py
tests/test_merc.py
tests/test_nemo.py
utils/misc.py

This comes out of a discussion with @htmlboss during his review of PR#614.
Drop `time_variable` attr from `Nemo`, `Mercator` and `Fvcom` classes in favour of accessing it as an attr on the `NetCDFData` instance that is used to construct instances of those classes. Access looks like `self.nc_data.time_variable` within instances of those classes, and like `dataset.nc_data.time_variable` or `ds.nc_data.time_variable` in code that uses `open_dataset()` as a context manager.
Likewise:
- drop `timestamps` attr in favour of accessing it like `dataset.nc_data.timestamps` or `ds.nc_data.timestamps` in code that uses `open_dataset()` as a context manager
- drop `timestamp_to_time_index()` method in favour of accessing it as `self.nc_data.timestamp_to_time_index()` within instances of …

Clean up attrs access among NetCDFData and Model-derived classes

---

data/netcdf_data.py
oceannavigator/dataset_config.py
oceannavigator/datasetconfig.json
routes/api_v1_0.py
tests/test_api_v_1_0.py
tests/test_dataset_config.py
tests/test_netcdf_data.py
tests/testdata/datasetconfigpatch.json

Add the ability to load datasets from ERDDAP servers via OPeNDAP dataset URLs. 
In particular, enable datasets to be loaded from the SalishSeaCast ERDDAP server. Those datasets require the extra optional feature of merging in a dataset that maps the model x-y grid indices to longitude-latitude.
It was the obvious path after having been immersed in the `data` modules doing the `open_dataset()` refactoring for PR#641,
This adds an optional `geo_ref` item to the datasetconfig shcema. I will update the wiki to add it tomorrow.
Presently there is only one of the SalishSeaCast tracer datasets (sea surface height) included in the dataset config. I can add more to this PR if I get them pushed before it is merged, but merging doesn't need to wait on them. They can just as easily be separate PRs. …

Erddap access

---

data/netcdf_data.py

Add chunks=200 to open_mfdataset.
From http://xarray.pydata.org/en/stable/dask.html
By default, open_mfdataset() will chunk each netCDF file into a single
Dask array...
The downside to this is that when you load data in from disk, the lazy
loading loads the entire netCDF file; when operating on a single file,
that's not a huge issue, but when you want a small chunk of data from 40
1GB files, you need to read 40GB from storage.
This wasn't an issue with the old netCDF and THREDDS setup because only
the required data was requested via OpenDAP.
The solution is to specify the 'chunks' parameter and let xarray/Dask
break up the dimensions into multiple smaller chunks that can be
accessed independently.
I did some experimental testing with 40 timesteps on the giops historical daily dataset. …

Add 'chunks' parameter to open_mfdataset.

---

oceannavigator/datasetconfig.json
plotting/colormap.py
routes/api_v1_0.py
tests/disabled/test_routes.py
tests/test_api_v_1_0.py
tests/test_colormap.py

Add dataset config and colour maps for SalishSeaCast biology model (SMELT) variables.
Also includes some drive-by code quality improvements in the `plotting.colormap` module and a new module of unit tests for that module.
Only way.
Colour maps are the same as those used on [SalishSeaCast site](https://salishsea.eos.ubc.ca/nemo/results/nowcast/biology/23mar20#tracer-fields-along-thalweg-and-near-surface) and, I think avoid visibility issues for ferry tracks and points as best as possible.
```sh
```

Add salishseacast biology

---

data/calculated_parser/functions.py
data/fvcom.py
data/mercator.py
data/model.py
data/nemo.py
data/netcdf_data.py
plotting/hovmoller.py
plotting/point.py
plotting/timeseries.py
plotting/transect.py
tests/disabled/test_fvcom.py
tests/test_merc.py
tests/test_nemo.py
utils/misc.py

Partially addresses #673 
tldr: virtual mooring is back (except for bottom depths)!
FVCOM will come at a later date since @geoffholden has work that depends on the fixes in here, so time is an issue. We don't have any operational FVCOM datasets currently, nor do we expect such datasets in the short-to-medium term.
**Note** timeseries for "bottom" depths won't be addressed in this PR for the above reasoning (i.e. remain broken). I believe there is some numpy axis magic possible to reduce the complexity of our bottom calculations and reduce the volume of code.
Our timeseries plots have been broken from some time so the basic idea behind these changes is to fix all that. At a lower level, I've tried to simplify the "data getter" functions in `Model.py` so callers can explicitly pass an …

Flesh out support for timeseries data.

---

oceannavigator/datasetconfig.json

Add dataset config for SalishSeaCast temperature and salinity variables.
Only way.
* Salinity is converted from model output of reference salinity in g/kg to user-familiar practical salinity in PSU. The conversion factor was provided by Rich Pawlowicz of UBC EOAS. It is correct for the Salish Sea, but is not generally applicable to ocean waters everywhere.
* Conservative temperature model output could not be converted to user-familiar potential temperature because Navigator is not yet using the [TEOS-10 equation of seawater](https://github.com/TEOS-10/GSW-Python). An issue to recommend a change to TEOS-10 will be created shortly.
```sh
python -m unittest `find tests -name "*.py" | grep -v …
```

Add SalishSeaCast temperature & salinity dataset config

---

data/class4.py
tests/test_api_v_1_0.py

#704 forgot to remove the FTP code in `data.class4.list_class4_models` so a crash was occurring. This PR just re-writes that function to use the same `glob` pattern established in #704.
I renamed `tests.test_api_v_1_0.test_class4_query_endpoint` to `tests.test_api_v_1_0.test_class4_models_endpoint`. It has also been enabled.
Simplest way.
I still don't like how we figure out which class4 file to open but that can be re-done another time.
Alternate models can be selected again:
```sh
```

Fix data.class4.list_class4_models crash

---

oceannavigator/datasetconfig.json

These variables weren't being calculated correctly because of some errors in `datasetconfig.json`
Wind variables have been removed since they only existed in the data for a short amount of time.
```sh
```

Water velocity magnitudes for historical giops

---

scripts/data_importers/argo.py
scripts/data_importers/concepts_drifter.py
scripts/data_importers/glider.py
scripts/data_importers/nafc_ctd.py
scripts/data_importers/seal.py

I'm not sure if you'll want these as part of the repo or not--probably so for 'sample' ones, but possibly not going forward if you get the data providers to manage their own importers.
These have been somewhat optimized for import speed (they're still pretty slow) by going around the ORM a little by using things like bulk_save_objects that doesn't follow relationships. This cuts down on a lot of DB transactions and speeds things up a lot at the expense of a little readability.
For anybody writing a new importer, my first suggestion would be to switch echo to True in init_db so you'll see every SQL statement printed to screen. With that set, you can use an in-memory sqlite database (URI sqlite:///:memory:) so that you can mess with things a fair bit without touching the proper DB. Even …

Observational Data Importers

---

data/utils.py

Replace `list(map(lambda ...))` construct with list comprehension. Combine `cftime.utime()` call into `cftime.num2date()` call. This makes a difference for all UI dataset change operations, but it is a hugely perceptible speed-up for the SalishSeaCast datasets that have >116,000 timestamps. Profiling:
Before:
```
cftime.num2date lambda: 35.860546588897705s
23.16.30.232 - - [02/Apr/2020 15:38:54] "GET /api/v1.0/timestamps/?dataset=salishseacast_3d_tracers&variable=temperature HTTP/1.1" 200 -
23.16.30.232 - - [02/Apr/2020 15:38:57] "GET /api/v1.0/variables/?dataset=salishseacast_3d_tracers HTTP/1.1" 200 -
23.16.30.232 - - [02/Apr/2020 15:39:00] "GET /api/v1.0/depth/?variable=temperature&dataset=salishseacast_3d_tracers HTTP/1.1" 200 -
cftime.num2date lambda: 35.24283742904663s
23.16.30.232 …
```

Speed up time_index_to_datetime()

---

plotting/map.py
plotting/plotter.py

Resolves #713 
Quiver overlays were broken, so I fixed them. Can't write unit test for this sadly yet since the test netcdf files doesn't have velocity component variables.
Cleanest way I could think of.
Feels like a bit of a hack, but we're expecting the magnitude equations to be given as `magnitude(x_var, y_var)` where x and y are defined in that order.
No magnitude
Magnitude by length
Magnitude by colour
```sh
```

Fix quiver plot + driveby code quality improvement

---

oceannavigator/datasetconfig.json
plotting/templates/pythonSUBSETtemplate.txt

Resolves #717
A user alerted us to a problem with subsetting Historical GIOPS, this fixes that.
Generated python subset scripts now build their API requests correctly
Historical GIOPS and GLORYS datasets can now be subset
```sh
```

Subset + Scriptgen fix

---

data/calculated_parser/functions.py
oceannavigator/datasetconfig.json

Enabled for all GIOPS and RIOPS datasets (except for those with "Historical" in their name).
Deep sound channel bottom definition:  Find and return the deep sound channel bottom (the second depth where the speed of sound is equal to the speed of sound at the sonic layer depth).
Most efficient way in terms of CPU and memory.
100% vectorized code keeps performance impact to a minimum.
* The code is not very intuitive but it's the fastest that it can be so take time to understand it.
Lat/Lon grid:
P/S grid:
```sh
```

Implement Deep Sound Channel Bottom calculated variable

---

.gitmodules

Alter the default [...]/oceannavigator/configs to use the off-site branch by default. As the number of instances grow it is better to adjust to meet the needs of the many to those of the few.

Set default [...]/oceannavigator/configs to use the off-site branch

---

bin/runserver.sh

During my search for ways to improve the user end experience. We should be launching two gunicorn processes per cpu processor found. The update to the runserver.sh script determines the number of processors an OS instance can see in the /proc/cpuinfo file multiplies that value by 2 and launches the number returned from the bc command.

Updated the runserver.sh script

---

bin/runserver.sh
data/calculated_parser/functions.py

As the title states, this is to help avoid any misunderstandings with the visual results, since these ocean features cannot occur at the surface.
* Sonic layer depth
* Deep sound channel axis.
Computationally quickest method that I know of. Just used numpy broadcasting to handle the masking since it's just a fast one-liner.
Nope.
Sonic Layer Depth:
Deep Sound Channel Axis:
```sh
```

Mask out surface values for some acoustic variables

---

data/class4.py
scripts/generate_class4_list.py

Fix class4 functionality breaking whenever root directory locations are changed.
Easiest way I could think of.
Nope.
```sh
```

Use os path functions for class4 files.

---

config/conda/index-tool-spec-file.txt

The hash information for the configs submodule was updated to use the latest version of the datasetconfig.json and the oceannavigator.cfg files. So that people installing and / or updating their version of the Ocean Navigator will receive the latest versions.
The conda spec file for the indexing tool was updated to exclude the version of openssl it would install. This package is not needed for the indexing code to function and the version of openssl is no longer available from the main conda channels we use for obtaining packages for our user environment.

Couple of updates

---

plotting/map.py

A number of end users and stakeholders have requested that the size of the font being used when the bathymetry data is viewed be increased and the color to be a more prominent.
The font size change was easier than selecting the color. In the end I removed the array values and used a direct call to a color scheme.
- [* ] I ran unit tests.
- [*] I've tested the relevant changes from a user POV.
```sh
```
Here are the results of running the unit tests;
```
======================================================================
ERROR: test_deepsoundchannel (tests.test_data_functions.TestDataFunctions)
---------------------------------------------------------------------- …
```

Changing the size and color used when plotting the bathymetry dataset.

---

data/netcdf_data.py
tests/test_netcdf_data.py
tests/testdata/datasetconfigpatch.json

Issue #769 revealed 2 ways in which a `subset` API call can result in a `ValueError`. This PR addresses one of them. A subsequent PR will address the other. 
In the case addressed here, @nsoontie identified in https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/issues/769#issuecomment-715537549 that the `ValueError` is due to the lons and lats variables being 1D arrays but `pyresample.geometry.SwathDefinition()` requires 2D arrays. The solution that @nsoontie came up with is to use `numpy.meshgrid()` to generate 2D lons and lats arrays.
It's a very simple, elegant 2-line solution to the problem.
It probably took me longer to cook up the unit test that demonstrates that the problem is resolved than it took @nsoontie to come up with the solution :smile: 
N/A
_Hint_ To run all …

Fix ValueError due to 1D lons/lats in subset API call

---

plotting/plotter.py

Optimize the ocean navigator performance in terms of response time
Based on the profiling results it shows this particular function (Compress/optimize the image) takes more time.
If it takes more time, then no point in optimizing, surprisingly without that function we can see improvement in response time based on the profiling results. 
N/A
After modification
Before modification

Image Optimization removed

---

oceannavigator/frontend/src/components/Class4Window.jsx
oceannavigator/frontend/src/components/PointWindow.jsx

In the hunt for ways to improve the performance of the profile plots in the Points UI overlay I found that the map generated when the Show Location checkbox is checked takes a significant percentage of the total rendering time. The changes in this PR make the default for Show Location in the Points and Class3 overlays unchecked.
I also considered changing the default checked setting of the Show Map checkbox in the Lines and Observation Tracks overlays, but decided that the map tiles in those overlays provide sufficiently useful information that they should remain. Please see the notes on the screenshots below. **I would like confirmation of that decision from people who are closer to the user community than I am.**
The backend code that runs when `showmap` is `true` takes 2 to 3 seconds, …

Change showmap default to false for Points & Class4 UI overlays

---

bin/launch-web-service.sh

`HOST_IP=$(ip addr show | grep -E "e(th|np|ns)" | grep inet | awk '{print $2}' | sed -e 's/\/[0-9]*//')`
this command is based on finding the eth, enp, and / or ens interface and then determining what the assigned ip is for a given interface. This command fails to work with other interface names. Particularly infiniband network interfaces which use the string ifb,
`HOST_IP=$(hostname -I | awk '{print $1}')`
the command determines what ip the machine has and prints it.
The desired behavior is obtained with a smaller command.
```
(navigator) ubuntu@u2004-onav-2:~/Ocean-Data-Map-Project$ ip addr show | grep -E "e(th|np|ns)" | grep inet | awk '{print $2}' | sed -e 's/\/[0-9]*//'
10.0.3.60
(navigator) ubuntu@u2004-onav-2:~/Ocean-Data-Map-Project$ hostname -I | awk '{print $1}'
10.0.3.60
```

Changed the way the host IP is determined.

---

data/netcdf_data.py
tests/test_netcdf_data.py

Issue #769 revealed 2 ways in which a `subset` API call can result in a `ValueError`. PR #774 addressed one of them. This PR addresses the other. 
In the case addressed here, @nsoontie identified in https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/issues/769#issuecomment-715598904 that the `ValueError` is due to the code trying to use longitude/latitude variables names in `Dataset.isel()` when it should be using x/y dimensions.
The solution Implemented in this PR was proposed by @nsoontie. It adds properties to the `NetCDFData` class to facilitate finding y and x dimension `DataArrays` in `Datasets` with a variety of dimensions via set intersections. 
1. Adding properties that provide a set of possible x/y dimension names gives us a single place to add dimension names from …

Fix ValueError due to "dimensions do not exist" in subset API call

---

oceannavigator/__init__.py

This change adds tagging of exception events captured by Sentry with and environment name that is read from the `SENTRY_ENV` environment variable. If that envvar is unset, the exceptions are not tagged, but they are still captured by Sentry.
Using an environment variable and the fact at the value returned by `os.getenv()` defaults to `None` gives us the flexibility to deploy Navigator instances with `SENTRY_ENV` not set with no negative consequences. When `SENTRY_ENV` is set, exception events captured by Sentry will be tagged with the environment name, enabling easy filtering of events from different environments; e.g. NAFC and `dory` production containers.
I propose that we use `NAFC` and `dory-prod` as environment names for the two deployments where we presently have Sentry activated. …

Add possible Sentry environment name from envvar

---

data/mercator.py
data/nemo.py

Instantiation of `pint.UnitRegistry` appears to take ~200ms every time the `depths` property is accessed.
However, code inspection and UI testing show that none of the features of `UnitRegistry` are being used on `depths`;
i.e. there are no accesses of `depths.magnitude` or `depths.units`, nor `pint` unit conversions on `depths`.
The `depths` property is accessed by several API endpoints, notably `tile_v1_0`, so eliminating that ~200ms can produce noticeably snappier performance on pages for which the caches are cold.
Timing statistics for `Mercator.depths` with `pint.UnitRegistry()` for single dataset variables initial page load with cold caches:
Statistic | Value
-- | --
count | 61
min | 0.142
mean | 0.253
median | 0.216
std dev | 0.110
max | 0.578
and without `pint.UnitRegistry()`: …

Drop unused `pint.UnitRegistry` in `Mercator.depths` & `Nemo.depths` properties

---

data/netcdf_data.py

There is a measurable performance cost to using `xarray.open_mfdataset()` with
chunking instead of `xarray.open_dataset()` without chunking when we are only
opening a single dataset.
Timing statistics for `routes.api_v1_0.tile_v1_0()` calls for single dataset variables initial page load with cold caches:
`xarray.open_mfdataset(..., chunks=200)`:
Statistic | Value
-- | --
count | 61
min | 0.817 s
mean | 2.496 s
median | 1.854 s
std dev | 1.679 s
max | 7.855 s
`xarray.open_dataset()` with no chunking:
Statistic | Value
-- | --
count | 61
min | 0.578 s
mean | 1.515 s
median | 1.451 s
std dev | 0.411 s
max | 2.491 s
I don't believe that the uniform chunking factor of 200 on all dimensions that is presently hard-coded is optimal when we are loading multiple datasets (either to retrieve …

Only use open_mfdataset() when there is >1 dataset

---

oceannavigator/__init__.py

We exceeded the 100k/mo transactions recorded threshold included in our Sentry subscription in 15 days after we started collecting transactions data for performance analysis.
The probability of a given transaction being sent to Sentry is set by the `traces_sample_rate` in the `sentry_sdk.init()` call; see https://docs.sentry.io/platforms/python/performance/sampling/. This PR makes it so that value is read from a new `SENTRY_TRACES_RATE` environment variable when the app starts up. If that envvar does not exist, or is empty, the value of `traces_sample_rate` will be 0; i.e. no transaction tracing from that deployment.
I propose that we `export SENTRY_TRACES_RATE=0.4` in the DAL-Prod deployment and leave `SENTRY_TRACES_RATE` unset in the DAL-Staging and NAFC deployments. We don't need …

Get Sentry traces_sample_rate value from environment variable

---

data/mercator.py
data/nemo.py

This should have been done in PR #791, but I missed it and didn't see that LGTM had flagged it before the PR got merged :frowning_face: 
Unused imports are distracting noise in the context of code comprehension.
No.
N/A
```sh
```

Delete unused UnitRegistry imports

---

data/class4.py
tests/test_data_class4.py

re: issue #796 The `/api/v1.0/class4/models/{class4_id}` endpoint always returns an empty list, resulting in no "Additional Models" selector section in the "Class 4 Settings" panel of the overlay.
This fix makes the code compatible with the `/data/class4/yyyy/yyyymmdd/` files storage scheme that is in use.
I also took the opportunity to modernize the code to use `pathlib`.
Broken:
Fixed:
```sh
```

Fix for issue #796 re: class4/models/{class4_id} API endpoint

---

tests/test_netcdf_data.py

To fix the Zarr unit test issue: https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/issues/801
Previous test Zarr file path was wrong, changed it to the correct path.
N/A
```sh
```

zarr unittest issue fix

---

plotting/class4.py

As @nsoontie recently observed, in the initial display of Class 4 profiles the model profiles are labelled as "Model". The profiles are always from the GIOPS class4 dataset, and, if additional model profiles are added to the plot, the "Model" label changes to read "GIOPS". So, this PR changes the legend label to be "GIOPS" from the outset.
This PR also updates the string formatting code in `plotting.class4.Class4Plotter.plot()` to use f-strings as much as possible. In one place an f-string is not feasible without complicating the code, so the update there is to `str.format()`.
Making the model legend consistently name the models shown is an improvement, as is modernizing the code to drop `%s` string formatting.
No.
Before:
After:
_Hint_ To run all python unit tests run the following …

Change Class 4 profiles legend to show GIOPS model label from the outset

---

data/class4.py
tests/test_data_class4.py

re: GitHub issue #798 and Sentry issue # PUBLIC-PROD-4
The class4 id in the API request ends with an index number that `data.class4.list_class4.forecasts()` is not expecting. Fixed that parsing by stripping of the index number. That revealed an [AttributeError issue](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/issues/798#issuecomment-742164788) a few lines later. It was resolved by adding `decode_times=False` to xarray.open_dataset(), consistent with how we open datasets in `netcdf_data.NetCDFData.__enter__()` because the netCDF times are decoded in our code.
Only way to make the code work.
Added unit test for part of `data.list_class4_models()` functionality.
The that generates the list of forecast dates for the frontend to use can't possibly add anything to the …

Fix for issue #798 re: FileNotFoundError in class4 forecasts API request

---

data/netcdf_data.py
tests/test_netcdf_data.py

Investigation of https://sentry.io/organizations/dfo-ocean-navigator/issues/2134767923 lead to the realization that a `sqlite3.OperationalError` was being masked by an `UnboundLocalError` in `NetCDFData.dimensions`. This PR increases unit test coverage for `dimensions`, and make its result of an empty list consistent for the cases of `OperationsError` and `FileNotFoundError`.
`UnboundLocalError` is a really bad code-smell. At least we now have a consistent outcome when there is a problem accessing sqlite3 and netCDF4 datasets.
The `OperationalError` is likely and indication of a deeper file system or container issue that is causing problems with access to the sqlite3 databases.
It is weird that `dimensions` is opening datasets at all. That should be the exclusive job of …

Fix UnboundLocalError netCDFData.dimensions

---

data/class4.py
scripts/generate_class4_list.py

Issue #757 and issue #785 are both a result of the the `scripts/generate_class4_list.py` script being old and out of sync with the way Class 4 files are now stored in data `/data/class4/` directory tree. This PR fixes that script, and modernizes its code and some related code in `data/class4.py`.
Class 4 indexing needed to be fixed, and modernizing old code is a good thing to do.
This PR includes sorting of the Class 4 files going into the index pickle such that the Class 4 date picker in the UI will have its default date set to that of the most recent available GIOPS Class 4 profiles file instead of a random date in the index.
Class 4 files prior to 2016-01-01 appear to be stored in encrypted tarballs like `/data/class4/2015/20151231/class4_20151231_GIOPS_CONCEPTS_1.1_profile.nc.gz.enc`. …

Update class4 index pickle generator script

---

oceannavigator/frontend/src/components/AreaWindow.jsx

Statistics functionality has been broken on the back end for a very long time, with not timeline on it being fixed. Let's just remove the ability for users to request it to reduce confusion.
It's the only way
Nope
Tab is gone:
```sh
```

Nuke stats tab

---

kml/point/ONC_Stations.kml
kml/point/Offshore_Oil_Operations.kml
kml/point/STRATOGEM_Stations.kml

Users request points from STRATOGEM and Ocean Networks Canada (ONC) stations in Salish Sea to be added to the Navigator's Points menu. These locations are frequently used for model vs. observation comparisons and are to be listed as 'ONC Stations' and "STRATOGEM Stations' in the menu.
'ONC_Stations.kml' and 'STRATOGEM_Stations.kml' files containing the lat/lon coordinates and name of each station were added to the /kml/points directory.  Also removed unused code from 'Offshore_Oil_Operations.kml' which does not provide any functionality for the Navigator. 
resolves #700, resolves #701 
kml files are found via functions in misc.py and the API so adding the kml files mentioned above to the /kml/points directory is all that is needed to include the station locations in the Navigator's points …

Add ONC & STRATOGEM stations to Points menu

---

oceannavigator/dataset_config.py
plotting/hovmoller.py
plotting/map.py
plotting/observation.py
plotting/plotter.py
plotting/point.py
plotting/profile.py
plotting/stats.py
plotting/stick.py
plotting/tile.py
plotting/timeseries.py
plotting/track.py
plotting/transect.py
plotting/ts.py

A 'scale_factor' attribute is given for many variables within the datasetconfig.json file which scales the data as needed for the presentation layer. While an important function it can be replaced by an equation which will provide the same functionality with more efficiency. 
References to 'scale_factor' were removed from datasetconfig.json, dataset_confi.py, and several plotting classes. In some instances where the scale factor was applied to the data along with other operations. For these cases the code was appropriately modified to preserve the necessary operations. 
closes #729 
Though 'scale_factor' can be depreciated just by removing references in datasetconfig.json, references in the calculation layer were also removed to help reduce the total amount of code in the Navigator.

Removed references to 'scale_factor'

---

data/transformers/geojson.py
data/utils.py
tests/data/transformers/test_geojson.py
tests/test_data_utils.py

Prerequisite for getting the `/data` API endpoint back up and running (#808)
* Provides functionality to serialize an xarray data array into a valid geojson dictionary.
* Added new `trunc` helper function to correctly truncate floating-point values to a given number of decimal places.
* Added relevant tests.
I decided to implement this as a free function to start instead of dumping it into `Data` as a virtual function for the sake of faster iteration....just wanna get #808 out before end of fiscal.
Ultimately I'd like to see syntax like `my_mercator_instance[0, 0, 5:10, 5:10].to_geojson()`, `...to_netcdf(nc_file_type)`, `...to_csv()`, etc... but `Data` is also missing `__getitem__` for proper slicing (so we can ditch `get_point`, `get_area`, etc, and simply keep the helper functions like …

Add GeoJSON transformer to data package

---

oceannavigator/frontend/src/components/Map.jsx
oceannavigator/frontend/src/components/OceanNavigator.jsx
oceannavigator/frontend/src/components/Options.jsx

Ignore the code formatting changes, it was automatically done by the VS code linter lol
The following bathymetry contour layers will be available:
* ETOPO1
* Did some basic refactoring (function extraction) to make this spaghetti code a little more digestible lmao.
* Started implementing this `shouldUpdate` framework to gradually improve perceived responsiveness of website. As more of these things are added, the number of components updated per react update cycle will reduce and thus will happen quicker. It's just standard react best practices that we haven't gotten around to implementing yet.
```sh
```

Add selectbox for choosing bathymetry layer source

---

config/conda/navigator-spec-file.txt

This new package was brought into the navigator toolchain to implement a better way of validating the type/formatting/etc of arguments passed to our python API.

Bringing in marshmallow version 3.11.0 from conda-forge.

---

data/calculated.py
data/netcdf_data.py
tests/test_calculated_data.py
tests/test_netcdf_data.py

While working on #829, I ended up discovering a nasty bug I introduced a few years ago (classic), where `CalculatedData.get_dataset_variable()` and `NetCDFData.get_dataset_variable()` were grabbing the wrong representation of the variable in a dataset, by returning a low-level `xarray.Variable`. I discovered this when I tried to do things like `my_variable['latitude']` and I was greeted with a nice old `TypeError: invalid indexer array, does not have integer dtype`. By playing around in `ipython` is when I realized my data types were different (because the `DataArray` allowed me to do `my_variable['latitude']`). Then I looked up the differences between a DataArray and a Variable and found these docs:
https://xarray.pydata.org/en/stable/terminology.html#term-DataArray
* Fixed bug.
* Added …

Bugfix: make `get_dataset_variable` return `xarray.DataArray` instead of `xarray.Variable`

---

.gitattributes
kml/area/SAR_Areas.kml

SAR requested 40 areas be included in the Ocean Navigator. A kml file containing the metadata for these areas was provided by the SAR group which was cleaned up before being added to the 'kml/area' directory of this branch.
The Navigator scans the 'kml/area' directory and populates the Area menu based on the files found.
```sh
```

Add SAR_Areas.kml to kml/area

---

plotting/colormap.py

The colormap for the Potential Sub-surface channel has been changed.
```sh
```

Changing the colormap for sub-surface channel variable

---

kml/area/SAR_Areas.kml
utils/misc.py

If the Navigator encounters an error when parsing a kml file it currently results in the point/line/area menu not being populated. Now that we have a kml file hosted on LFS this is more likely to happen to users if they try to run the Navigator without LFS on their system or before the file is downloaded. Adding a try statement to `list_kml_files` in `misc.py` allows the Navigator to skip kml files when it encounters a parse error and continue to populate the relevant menu.  
Also removed 'Final' from SAR Areas name.
Seemed to be the easiest way to ensure that the Navigator will continue to read in kml files in the event of an error.
```sh
```

Skip broken kmls

---

tests/test_api_v_1_0.py

it was testing bottom depth but was named all_depths...copy paste error from a couple years back
```sh
```

Fix mis-named integration test

---

bin/runserver.sh
data/netcdf_data.py
oceannavigator/__init__.py

* Remove `chunks` parameter from open_mfdataset.
* Removed `num_procs` parameter from `resample_gauss`.
* Reduce `WORKER_THREADS` in `runserver.py` from 5 to 2.
* Configure global dask settings on startup to conditionally read vars from cfg file or set sane default otherwise
Related to https://github.com/DFO-Ocean-Navigator/configurations/pull/23
Just following Doug's findings.
Total system thread count has dropped by about by ~15% with these changes with no perceivable difference in website loading speed.
n/a
```sh
```

Some performance tweaks

---

data/sqlite_database.py
plotting/timeseries.py

**Resubmission of PR#843 to avoid messy commit history
CCG requested that we include water velocity bearing in timeseries csv's. When working on adding this data to the csv output I also found two other problems that are addressed here:
1. The  `Save Image - CSV` function on the Virtual Mooring window gives an Internal Server Error in all instances.
2. The order of point data in the Virtual Mooring timeseries changed each time I restarted my local Navigator instance which lead to concerns about the integrity of VM data. This was also observed when comparing VM plots on the production and staging sites - recreating the same plot on each produced different results - and when changing the start and end times of the timeseries plots. 
It looks like work on including bearing in the water …

Add bearing to magnitude timeseries csv and ensure timeseries data is ordered 

---

oceannavigator/frontend/package.json
oceannavigator/frontend/yarn.lock

The following JS packages have been updated due to security alerts;
* css-what@2.1 ==> css-what@^5.0.1
* is-svg@^2.0.0 ==> is-svg@^4.2.2
* trim-newlines@^1.0.0 ==> trim-newlines@^3.0.1
* yargs-parser@^4.2.0 ==> yargs-parser@^5.0.0-security.0

Select JS packages have been updated due to security alerts

---

routes/api_v1_0.py
routes/schemas/__init__.py
routes/schemas/depth_schema.py
routes/schemas/quantum_schema.py
routes/schemas/timestamps_schema.py
tests/routes/schemas/test_depth_schema.py
tests/routes/schemas/test_quantum_schema.py
tests/routes/schemas/test_timestamps_schema.py

Make our API self-documenting.
Builds on the work of the first schema-ed API endpoint being `/data`.
Adds `marshmallow` schemas to the following API endpoints:
* `quantum`
* `timestamps`
* `depth`
* There are other query-based endpoints but they're not as easy to apply a schema too since I'm not 100% sure what they're types are supposed to be.
* Followed the same approach as I did in the `/data` endpoint.
These schemas will auto-generate and return helpful error messages to the user in the event they mess up:
No change to user-facing website:
```sh
```

Add schemas to some endpoints

---

routes/api_v1_0.py

#857 Introduced a bug where the depth request fails in some circumstances where our terrible test coverage doesn't cover.
Tested circumstances locally and it's fixed.
```sh
```

Fix bug in depth endpoint

---

routes/schemas/timestamps_schema.py

#857 exposed a frontend bug (surprise surprise) where jQuery is sending a hidden `_=1625711072192` parameter as part of the timestamps payload in `TimePicker.jsx`....not sure why it's doing that. Anyway there's no further security risk as we just silently ignore this unknown value. 
By default `marshmallow` raises an error when it encounters a URL parameter that hasn't been explicitly defined in the schema...a security feature. We've been accepting anything and everything up to this point so this bug has probably been around for several years...
* Followed: https://marshmallow.readthedocs.io/en/stable/quickstart.html#handling-unknown-fields
Tests would have never caught this anyway because this might be a jQuery bug...
Works now (note the `_` field on the right side of the URL):
_Hint_ To …

Exclude unknown fields in TimestampsSchema

---

routes/api_v1_0.py
routes/schemas/__init__.py
routes/schemas/generate_script_schema.py
tests/routes/schemas/test_generate_script_schema.py
tests/routes/test_api_v_1_0_generatescript.py
tests/test_api_v_1_0.py

Building on the work in #853 
* As the title says.
* Re-write integration test for this endpoint too (`python -m unittest tests/routes/test_api_v_1_0_generatescript.py`)
Same as #857 
* One test in `tests/routes/test_api_v_1_0_generatescript.py` is skipped because @BaruaSourav is working on the template for R CSV downloads.
Checked download buttons for python and R:
```sh
```

Add schema to generatescript endpoint

---

oceannavigator/frontend/package.json
oceannavigator/frontend/webpack.config.js
oceannavigator/frontend/yarn.lock

Followed webpack guides for v1->v2->v3->v4.
Latest v4 version is `4.46.0`
Avoiding v5 for now since some dependencies we use still aren't ready for v5. Plus v5 was only released during the last quarter of 2020 so it's still pretty new.
* _Dwayne I'd suggest doing a `yarn dev` and a `yarn build` in two separate fresh environments to ensure this crap is actually working before approving + merging._
* We might start getting more automatic dependabot updates now that we're out of ancient history for webpack...Plenty of other fossils to be updated though.
* `yarn build` WORKS AGAIN :partying_face: 
* Some of the dependencies have not been updated to their latest versions since they would depend on webpack 5. But they are at their latest compatible versions for webpack v4.
* Took a few hours …

Update `webpack` to latest v4

---

oceannavigator/frontend/src/components/OceanNavigator.jsx
oceannavigator/frontend/src/remote/OceanNavigator.js

Part of moving away from ajax to axios for making remote api calls and centralizing where these calls are implemented.
Nope
No change to expected behaviour
Changing datasets:
```sh
```

Use axios for fetching timestamps and variables in OceanNavigator component

---

oceannavigator/frontend/package.json
oceannavigator/frontend/src/components/Map.jsx
oceannavigator/frontend/yarn.lock

to ensure pre-defined points, lines, and areas are rendered when clicked
Justin and Sourav noticed recently that when a user clicks on an item in the pre-defined point, line, and area menus, nothing is rendered on the main map unless the user pans/drags the map with their mouse (i.e. telling OpenLayers to refresh all map layers based on a request for an "animation frame"). At some point in the past, OpenLayers implemented an optimization to perform conditional map updates based on some arbitrary conditions, so when we updated to ol 6, we silently inherited this behaviour :facepalm: 
This PR restores the initial functionality we had where data is immediately drawn on the map when clicked.
* Also updates `ol` to it's latest version. The updates include some performance improvements to …

Update `ol` from 6.5.0 to latest 6.6.1 & conditionally force a refresh of map's vector source

---

oceannavigator/frontend/src/components/Map.jsx

Resolves a crash in OpenLayers where error 68 was thrown in the javascript console and a black map screen was displayed for Arctic and Antarctic projections.
https://openlayers.org/en/latest/doc/errors/#68
Only way to fix this. Guessed that this argument is now explicit and guess I was right lmfao.
Nope.
Arctic:
Antarctic:
```sh
```

Explicitly set projection of hi-res bathy layer in Map `componentDidUpdate`

---

oceannavigator/frontend/src/components/Map.jsx
oceannavigator/frontend/src/components/OceanNavigator.jsx
oceannavigator/frontend/src/components/PlotImage.jsx
oceannavigator/frontend/src/components/fail.js

A change to the interaction between Babel and Webpack caused our images loaded via require to break silently.
Only way.
JS sucks
Images show up again:
```sh
```

Fix images loaded via webpack failing to load

---

oceannavigator/frontend/src/components/AreaWindow.jsx
oceannavigator/frontend/src/components/DatasetSelector.jsx
oceannavigator/frontend/src/components/LineWindow.jsx
oceannavigator/frontend/src/components/MapInputs.jsx
oceannavigator/frontend/src/components/OceanNavigator.jsx
routes/api_v1_0.py

Fixed the bug in the datasetconfig which caused the velocity arrows to point the wrong way. https://github.com/DFO-Ocean-Navigator/configurations/pull/27
Only way.
Did a bit of cleaning to hide the quiver selector in the point, line, and area windows since it's useless there.
Notice the arrows lining up with the area window plot. 
Main map (double resolution...every second point...this pr will deploy every fourth point):
Area window:
If you zoom out you can really see the current structure. really cool stuff
```sh
```

Re-enable main map quiver arrows

---

scripts/pregen_tiles.py

Applicable to all GIOPS and RIOPS datasets, at the surface, for the first timestamp found for each dataset (so for forecasts, today), for temp salinity water x water y and magnitude variables
Bit slow but I'm not sitting on top of the data. May take a couple of hours so best run during the night. We're paying for the electricity so might as well use it LOL.
We've got lots of RAM so let's warm up the cache to make stuff fast.
Invoked by `python scripts/pregen_tiles.py --url <url>`
* `python scripts/pregen_tiles.py --url http://10.5.166.251:5000`
* `python scripts/pregen_tiles.py --url https://navigator.oceansdata.ca`
Will be expanded in the future for other datasets, variables, depths, and times. Just getting some hack out quickly for a fast win.
Will execute remote requests in batches of …

Add script to pre-gen tiles

---

data/mercator.py

When making an API call like `/api/v1.0/variables/?dataset=giops_fc_10d_2dll` we want to return a list of variable but we don't actually need any particular variable's data loaded from the disk.
For Mercator models, there was an implicit assumption that there would *always* be a latitude/longitude variable available.  However, if we have haven't selected any particular variables (like during this API call that is concerned with the dataset level and not anything about a particular variable).
This PR handles the KeyError exception when no latitude/longitude variable is available and prints out an warning/information message instead.

Fixes #893

---

oceannavigator/frontend/package.json
oceannavigator/frontend/yarn.lock

No issues found with upgrading between versions pertaining to package dependencies.

Upgrading the version of tar from ^2.0.0 to ^4.4.18.

---

oceannavigator/frontend/src/components/AreaWindow.jsx
oceannavigator/frontend/src/components/OceanNavigator.jsx

As described in Issue #896, the interpolation settings are not updated when the variable is changed from the Area Window. As a result, the area plot does not use the correct settings when PSSC is selected.  The `updateOptions` function used to track changes to the interpolation and bathymetry settings was not being passed to the `AreaWindow` component, preventing the Navigator from updating the interpolation type when variables are selected from the Area Window.  
Adding `updateOptions` to the AreaWindow's properties allows the DatasetSelector component to pass the interpolation options back and draw the area plot with the correct settings. This fixes #896.

Add updateOptions to AreaWindow props

---

oceannavigator/frontend/src/components/AreaWindow.jsx
oceannavigator/frontend/src/components/ComboBox.jsx
oceannavigator/frontend/src/components/DatasetSelector.jsx
oceannavigator/frontend/src/components/OceanNavigator.jsx
oceannavigator/frontend/src/components/PointWindow.jsx

The Navigator has been crashing when changing variables from the Virtual Mooring tab in the Point Window. This underlying error occurs in the MapInput component which is getting passed an empty 'options' object which should contain updated interpolation settings for the newly selected variable. Initially, these settings were passed back from the variable ComboBox via the onUpdate callback but this function wasn't updating the 'options' state. To correct this we now pass the updateOptions callback to the variable ComboBox via the AreaWindow and PointWindow components so that they can directly update the `options` object. The DatasetSelector contained similar functionality but since this component also relies on ComboBoxes to select variables this was removed to avoid redundancy.  This …

Fix variable selector in virtual mooring tab

---

data/calculated_parser/functions.py

* Corrected the order of east_vel and north_vel in the call to np.arctan2()
* Modified the order of north_vel and east_vel in bearing function definition to match how it is currently being called in datasetconfig.json
The bearing calculation uses the function ```np.arctan2(y, x)``` where the order of the arguments matters - that is the north_vel (or y-like) variable must be first. This pull request corrects the original implementation which passed the east_vel (or x-like) variable first. 
This error did not appear to cause an issue because the order of the east_vel and north_vel was swapped in the call to  bearing() in datasetconfig.json. 
This change will improve debugging and code readability.
It is correct.
In calls to bearing(), the order of the variables matters!
When working in …

Modified bearing equation to correct order of east_vel and north_vel

---

data/calculated_parser/functions.py

Nancy found that bearings in the north-west quadrant (270-360 deg) were displayed as negative values in quiver arrow tool tips (Issue #907). 
It looks like the line `bearing.values[negative_bearings] += 2 * np.pi` wasn't updating the bearing xarray.variable object so I replaced it with an xr.where function:`bearing = xr.where(bearing < 0, bearing + 2*np.pi, bearing)`. This gives us positive values for all quivers regardless of direction.
Fixes #907
The built-in where function can replace directly replace values in an xarray object based on a conditional. This seems like a good use case for it.

Replace negative bearing values in quiver tooltip

---

oceannavigator/frontend/src/components/DatasetSelector.jsx

When working through the pre-release checks yesterday I found that the Navigator crashed with this error when trying to review datasets 5 and 8:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'id')
at DatasetSelector.render (DatasetSelector.jsx:117)
at finishClassComponent (react-dom.development.js:17160)
at updateClassComponent (react-dom.development.js:17110)
at beginWork (react-dom.development.js:18620)
at HTMLUnknownElement.callCallback (react-dom.development.js:188)
at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
at invokeGuardedCallback (react-dom.development.js:292)
at beginWork$1 (react-dom.development.js:23203)
at performUnitOfWork (react-dom.development.js:22154)
at workLoopSync (react-dom.development.js:22130)
``` 
Testing with other 2D …

Restore 2D dataset functionality

---

data/netcdf_data.py

We were notified that users are unable to subset area data using NetCDF-3 formats for calculated variables. When creating a subset from one of these variables the Navigator attempts to add the attributes from the datasetconfig.json as variable attributes in the resulting NetCDF file. This includes the 'dims' attribute is a list of strings describing the dimensions used for the variable calculation. It seems that xarray will try to encode variables like this one using the _NC_STRING_ format which is only compatible with NetCDF-4 files, causing the error. More detail can be found in Issue #919.
Closes #919 
My initial approach was to cast the 'dims; variable to another datatype to see if xarray would encode it using a compatible format however nothing seemed to work. In the end I felt that …

Restore NC3 Subsetting for Calculated Variables

---

bin/launch-web-service.sh
bin/runserver.sh

Removed the logging information from the launch-web-service.sh script as
runserver.sh now contains a Gunicorn --log-file definition. As well, the
number of Gunicorn worker threads has been reduced from 2 to 1.

Updates to a couple of service scripts

---

oceannavigator/frontend/src/components/AreaWindow.jsx
oceannavigator/frontend/src/components/ComboBox.jsx
oceannavigator/frontend/src/components/DatasetSelector.jsx
oceannavigator/frontend/src/components/LineWindow.jsx
oceannavigator/frontend/src/components/Map.jsx
oceannavigator/frontend/src/components/MapInputs.jsx
oceannavigator/frontend/src/components/OceanNavigator.jsx
oceannavigator/frontend/src/components/PointWindow.jsx
oceannavigator/frontend/src/components/Range.jsx
oceannavigator/frontend/src/components/lib/SelectBox.jsx
routes/api_v1_0.py

* Re-jigged the state update logic in `OceanNavigator` to be more understandable.
* Moved the update interpolation options code to the `OceanNavigator` component to keep our `SelectBox` component as generic as possible.
* Added a new field (`two_dimensional`) to the `variables` API response to allow the front end to filter 3D or 2D variables without requiring another API call.
* Small refactor of the variables API endpoint to simplify conditional logic and remove code duplication.
* Fixed a bug in the `Map` component where the colourmap bar wouldn't be created when the website first loads. This bug was introduced when I simplified the state update logic in `OceanNavigator` to follow React best practices, so technically the fact the colourmap bar was showing before my refactor is actually …

Stop duplicate API calls for Variables dropdown

---

data/calculated.py
data/calculated_parser/functions.py
data/netcdf_data.py
oceannavigator/frontend/src/components/AreaWindow.jsx

Continuing the work started in PR #920 which allowed users to export subsets in all NetCDF formats but didn't fix issues that prevented users from creating subsets with multiple variables or over a time range. 
A major component of this issue was the `calculated.isel()` function which returned xarray DataArray objects without properly defined dimensions. These objects were given xarray's default dimension names (`[dim_0, dim_1,...]`) which caused conflicts when variables of varying sizes were added to the subset xarray object. Generally this occurs when sub-setting 2D and 3D calculated variables. In this situation `dim_0` would often correspond to the latitude of the 2D variable but the depth of the 3D one. These dimensions generally have different sizes and so cannot be merged.  
Another …

Fix subsetting for multiple variables and over time ranges

---

oceannavigator/__init__.py

Added the option to enable the Werkzeug profiling middleware on the Navigator using a new `WSGI_PROFILING` option in the 'oceannavigator.cfg' file. Enabling this option will profile each API request the Navigator receives and write it to a new directory names 'profiler_results' in the Navigator's root directory. These files are cProfile output which can be really helpful in benchmarking and finding bottlenecks in the code, They can be analyzed in python or with a viewer such as SnakeViz or Tuna (shown below). 
Profile output:
A profile icicle plot viewed in Tuna:
This functionality is already provided via Flask so this work just gives us a easy way to enable it when required. Profiling can add a fair amount of overhead to the application so having the option to enable it is essential. 
- …

Add Werkzeug profiling middleware

---

oceannavigator/frontend/package.json
oceannavigator/frontend/yarn.lock

Reverts DFO-Ocean-Navigator/Ocean-Data-Map-Project#918
breaks the timepicker

Revert "Bump jquery-ui from 1.12.1 to 1.13.0 in /oceannavigator/frontend"

---

oceannavigator/frontend/src/components/Map.jsx

Artifact from a messed up rebase that causes a white screen
The scale viewer is still being manually added on line 679 which is the intended behaviour.
Restores previous functionality. Thanks Justin for pointing this out!
Only way.
```sh
```

Remove erroneous call to `addControl` in Map component

---

oceannavigator/frontend/src/components/DatasetSelector.jsx

Second of the three bugs Justin flagged for me to take a look at.
Left-over typo from the refactor.
Caused a white screen crash on page load
The `datasetVariables` reference in the `props` is the old way of getting the dataset variables; before the `DatasetComponent` selector itself handled the fetching of that list. 
Did a quick search for `this.props.datasetVariables` in the `DatasetSelector` file and there are no more instances.
Nope
3D variables are still filtered through in the point window where appropriate
```sh
```

Bugfix: Fix reference to non-existant prop in DatasetSelector

---

oceannavigator/frontend/src/components/AreaWindow.jsx

Follow up to #926 
The fixes the last of the three issues Justin notified me about that were related to the big front end refactor that was merged a couple of weeks ago.
Unused code so I deleted it
Nope
Previous behaviour restored
```sh
```

Bugfix: Remove unused function binding in `AreaWindow`

---

oceannavigator/frontend/src/components/DatasetSelector.jsx
oceannavigator/frontend/src/components/lib/SelectBox.jsx

Follow up to #926 where I removed the dataset help button but forgot to add it back
Added this help button as an optional feature of the new dropdown component, so this button could appear elsewhere for extra help.
```sh
```

Revive dataset help button

---

routes/api_v1_0.py

Prior to  #925 the `calculated.__getitem__()`  function retuned calculated objects with minimal coordinate and dimension data - generally just lat and lon. Since these changes, this method now returns data with all available coordinates and dimensions, including depth and time which allowed us to fix the subsetting issues described in the PR. The `data_array_to_geojson` function expects arguments in the old format so these additional coordinates need to be dropped.  
Using xarray's `squeeze()` method we can drop the time and depth dimensions from the DataArray object before passing it to `data_array_to_geojson`.  Because these dimensions have unit length calling squeeze with `drop=True` just broadcasts the DataArray to a 2D shape with lat and lon coordinates while dropping the other …

restore quiver arrows

---

oceannavigator/frontend/src/components/DatasetSelector.jsx

As discussed in issue #946 ,the time range selector used for virtual mooring and hovmoller plots defaults to the first and last available timestamps. Since bringing more historical data into the Navigator this results in front end querying timeseries plots with thousands of timestamps for some datasets when a user first opens either the virtual mooring or hovmoller plot windows. These datasets include RIOPS, CMEMS, and SalishSeaCast. 
To fix this, we check the number of available timestamps for a given dataset and set the default timepicker values to the most recent 20 if more are available. This allows the Navigator to quickly produce a plot for the users when they open these tabs. They can then request longer timeseries' if needed. This fixes #946.
This allows the Navigator to quickly …

Limit default time selector range

---

oceannavigator/frontend/src/components/MapInputs.jsx
oceannavigator/frontend/src/components/OceanNavigator.jsx

Related to #950 
This may resolve the issue of the compare mode not updating, given in `OceanNavigator.jsx` we expect the id to be either `dataset_0` or `dataset_1`.
Can't test this locally since my container is way out of date with the package updates.
```sh
```

Fix `id` of right map dataset selector

---

plotting/map.py

Found two basemap related issues when testing the area plot functionality of the updated toolchain on the staging site. The first is related to basemap's `drawcoastlines` method which fails when the selected area contains zero coast lines. To avoid calling this method unnecessarily we can check for area for polygons in the `basemap.coastsegs` attribute. 
The second issue is related the the normalization used when drawing area bathymetry with little variation. It seems that the object produced by `matplotlib.colors.LogNorm` has changed a little and is no longer compatible with basemap in this situation. The fix here was to recreate the same normalization object using matplotlib's `FuncNorm` function. This produces the same result without the error. 
These are the most minimal changes I …

Basemap bug fixes

---

oceannavigator/frontend/src/components/AreaWindow.jsx

Per issue #951 the dataset selector wasn't updating the compare dataset area plot after it was initially created. It looks like this problem was due to the DatasetSelector's onupdate method which was set to the AreaWindow's onLocalUpdate method. This method does not update the values of dataset_0 and dataset_1 of the parent components when the dataset/variables are changed. Using `this.props.onUpdate` instead passed these values to the parent classes and updates the plots correctly. 
This change follows the approach used in other components such as LineWindow. 
```sh
```

Change areawindow datasetselector onupdate method

---

oceannavigator/frontend/src/components/AreaWindow.jsx

When working on PR #958 I forgot to modify `plot_query` so that it gets data from the AreaWindow's updated props instead of state since the DatasetSelector now modifies props instead.  As a result the left map dataset selector panel couldn't update the plot when compare datasets was selected though the right map panel worked as expected. 
The dataset_0 parameters are now only updated in props so we need to grab them from there. 
Starting to appreciate why people dislike JS...

Get area window plot query data from updated props

---

routes/api_v1_0.py

Since updating our python tool chain we've been getting the following error when trying to add water velocity quivers to the main map:
```
Traceback (most recent call last):
...
File "/home/ubuntu/Ocean-Data-Map-Project/routes/api_v1_0.py", line 351, in get_data_v1_0
send_file(f, 'application/json')
...
ValueError: Files must be opened in binary mode or use BytesIO.
```
After a bit of reading the Flask/Werkzeug docs it seems that this error was always an issue for us but prior to Flask 2.0 `send_file` would send an empty file instead of raising the `ValueError` . The reason this wasn't an issue for us before is that we never actually returned the send_file object. Instead we proceeded through the function and re-calculated the quiver arrows, essentially rendering our cached geojson data …

Use cached quiver variable data

---

routes/api_v1_0.py

Fixes a bug where a 2D dataset variable is incorrectly sliced...it has no depth
Seems like the most logical approach.
* This will allow us to expand our offerings of velocity arrows to more datasets. PRs for those will be put up after this is merged.
Tested on 2D CCG RIOPS which was previously crashing
3D still works:
```sh
```

API: Enable /data to also return 2D variables

---

plotting/map.py

Another basemap related error only seems to affect the WCPs-GLS Great Lakes dataset. `self.basemap.coastsegs` returns an array of empty arrays for some reason so the check to see if coastlines need to be plotted passes which causes a ValueError. Added a second check into the first element of coastsegs to handle this case.
This works for in cases where there area is in open water and `coastsegs = [ ]` and areas enclosed by coaslines where `coastsegs = [[ ]. [ ], ...]`

Fix great lakes area plots

---

routes/api_v1_0.py

Fixes a bug where a 2D dataset variable is incorrectly sliced...it has no depth

Bringing back in Nabil's API: Enable /data to also return 2D variables code from PR #961

---

oceannavigator/dataset_config.py
routes/api_v1_0.py

Adds a new attribute `vector_arrow_stride` available in the datasetconfig file to control the density of arrows being shown in the UI.
* If not specified in the config file, it defaults to 4.
To specify it for CIOPS East for example:
```json
...
"help": "...",
"variables": {},
"vector_arrow_stride": 8
}
```
no change in behaviour
```sh
```

Make stride of geojson conversion configurable through datasetconfig

---

data/calculated.py

I forgot to account for the : operator when I made the changes in #972 which results in an empty slice index when passed into `__getitem__`. To avoid this I'm just taking the array shape from the coordinates since we really only need to reshape the array when it's dimensions differ from it's parents dimensions/coordinates.
Makes more sense to get the final array shape from the coordinates since we're reshaping the array to match these anyway.

Fix calculated indexing

---

data/netcdf_data.py
routes/api_v1_0.py

Related to #886 
Fixing some deprecation warnings emitted when running tests: https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/runs/5523667443?check_suite_focus=true#step:8:1
np.int, xarray.drop, flask attachment_name
Followed suggestions from test logs.
```sh
```

Fix some python deprecations

---

routes/api_v1_0.py

Related to #886 
`cache_timeout` is deprecated.
```sh
```

Fix `cache_timeout` -> `max_age` deprecation warning

---

config/conda/environment.yml

I don't think this is used in the navigator and adds 100mb+ of files downloaded.
Are these packages actually needed? @JustinElms 
```sh
```

Remove Qt from conda environment

---

data/netcdf_data.py
routes/api_v1_0.py
tests/routes/test_api_v_1_0_get_data.py
tests/testdata/datasetconfigpatch.json

Ran into the following crash that #988 revealed
```
======================================================================
ERROR: test_data_endpoint_with_bearing (tests.routes.test_api_v_1_0_get_data.TestAPIv1GetData)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/nabil/Ocean-Data-Map-Project/tests/routes/test_api_v_1_0_get_data.py", line 37, in test_data_endpoint_with_bearing
res = self.app.get(
File "/home/nabil/miniconda3/envs/navigator/lib/python3.8/site-packages/werkzeug/test.py", line 1127, in get
return self.open(*args, **kw)
File "/home/nabil/miniconda3/envs/navigator/lib/python3.8/site-packages/flask/testing.py", line 216, in open
return super().open(  # type: ignore
File …
```

[Bugfix] Ensure int is returned in `NetCDFData#timestamp_to_time_index`

---

routes/api_v1_0.py

The production LXD containers are using over 96GB of RAM. Each gunicorn process is hogging about 4GB. That's not good so we need to see what objects are taking up memory.
* Introduces a new `/api/dump-heap-memory` endpoint which will generate a file in `/tmp/` containing a dump of all Python objects in memory with the `__class__` attribute.
GET requests will return a pickle file with the heap memory for the python process dumped inside. Can be viewed via 
```python
with open(memory.pickle, 'rb') as dump:
obj = pickle.load(dump)
```
```sh
```

Add `/api/dump-heap-memory` endpoint

---

oceannavigator/frontend/src/components/Map.jsx

Fixes issue #999 
The query was using bathymetry type instead of that selected projection type. Changing `currentBathy` to `currentProj` fixing the problem.
```
updateBathymetryLayer(currentProj, currentBathy) {
let source = null;
switch (currentBathy) {
case "etopo1":
default:
source = new olsource.XYZ({
url: (
`/api/v1.0/tiles/bath/${currentProj}` +
"/{z}/{x}/{y}.png"
),
projection: currentProj,
})
break;
}
```
```sh
```

Cannot generate bathymetry tiles for polar projections #999

---

oceannavigator/frontend/src/components/Map.jsx

This will reduce the number of requests being sent to the python server and help reduce unnecessary load. By setting to 1 it will pre-load tiles for the current zoom level.
https://openlayers.org/en/latest/apidoc/module-ol_layer_Tile-TileLayer.html
We don't need to be pre-loading 7 zoom levels of tiles at a time.
```sh
```

Reduce map preload levels from 7 to 1

---

data/__init__.py
oceannavigator/__init__.py

See #1003 for graphs
Removes one source of unbounded memory growth. This decorator isn't even being used correctly since the function arguments are being hashed based on memory location and so we never see a cache hit.
Fastest way to stem the bleeding until we have time to properly implement a memcached-backed `open_dataset` in the future.
```sh
```

Remove `hashable_lru` decorator from `open_dataset`

---

.vscode/launch.json

Added `ONav` and `Python: Current File` options to VS Code's _Run and Debug_ button. The first allows VS Code users to launch the Navigator with debugging via the `runserver.py` script. The other runs the currently selected python file - useful when running/testing scripts.

Add Navigator option to Run and Debug button in VS Code

---

plotting/basemap.py
plotting/utils.py

To keep our datastore organized we'll keep the shapefiles needed for Cartopy in a subdirectory of `SHAPE_FILE_DIR` called _cartopy_resources_ per Dwayne's suggestion. This PR just updates the paths when importing the land geometry shapefiles

Update Cartopy resource directory

---

plotting/templates/rCSVtemplate.txt
plotting/templates/rPLOTtemplate.txt

We found that the R scripts were downloading garbage data. It appears that the files were corrupted on downlead plus the csv script was actually downloading a plot image and just saving it with a '.png' extension. Setting `method="auto"` and  `mode="wb"` in the download.file function appears to resolve the file corruption issue. Tested both scripts on Ubuntu 20.04 and Windows 10.
Using the auto method gives R some flexibility to select the download method based on the user's OS. Otherwise we'd have to specify a method that might not be available on the user's system.

Fix R API scripts

---

.github/workflows/lint_python.yml

Reduces useless CI runs when python files aren't changed. same change is coming up with the tests.
```sh
```

Only run lint_python action when python files are edited

---

.github/workflows/python-tests.yml

Reduces CI runs and speeds up development cycles.
```sh
```

Only run python-tests action when python files are edited

---

oceannavigator/frontend/src/components/MapToolbar.jsx

The link to the API documentation is currently broken so the button should be removed until the documentation becomes available.
I just commented out the relevant code so that we can easily restore it once docs become available. 

Remove API button from map toolbar

---

plotting/basemap.py
plotting/utils.py

Error handling is needed for deployments where the necessary Cartopy images and shapefiles may no be available, i.e. for our  automated CI testing. If these files cannot be located, the Navigator will fall back to using Cartopy's built-in resources.
If these resources are unavilable it only makes sense to use those provided by Cartopy. This should allow GitHub actions to complete CI testing.  
If the bluemarble image (top) is missing plot image with Cartopy's included features (bottom)

Handle missing Cartopy resources

---

.github/workflows/python-tests.yml
oceannavigator/__init__.py
routes/api_v1_0.py

Adds an API endpoint that returns the Git version of the Navigator's code via `/api/v1.0/gitversion`. This can be useful for testing/profiling the Navigator and comparing performance of different releases. The git version is also added to the Response Headers so that we can grab it from individual API requests.
GitPython provides a more direct approach but may leak resources. I came across other approaches which account for system environment but since the Navigator is only deployed in nix systems this approach seemed most straight forward.

Add Git Version endpoint to API and Response Header

---

plotting/timeseries.py

The issue with VM time series plotting option with selecting/importing multiple points is fixed by looping through all the selected points. 
The VM time series plotting with selecting/importing single points is working fine as expected below;
But For multi points selection or importing multi points the UI is getting error message from backend plotting. The details message with screen shots are below:
The wrong dimension in X and Y plotting with multi points selection originated in the timeseries.py file plotting function. 
- [y ] I've tested the relevant changes from a user POV.
```sh
```

VM Plotting Issue With Multi Point Selection

---

oceannavigator/frontend/src/components/AreaWindow.jsx

This PR resolved the issue  #971 - Subset panel does not update when dataset is changed within the area window.
The variable options in the subset panel are not updated when the dataset is changed from within the AreaWindow component. In the screenshots shown in issue # 971,  the user changed datasets from RIOPS 3D Forecast to GIOPS 10 Day 3D forecast and pressed the GO button but the subset panel remains unchanged. The most notable issue is that these datasets are hourly and daily forecasts we should see the time pickers update to accommodate the time resolution of the second dataset. Clicking the 'save' button on the subset panel will download a netcdf file containing data from the first dataset.
- Resolved the subset variable update issue 
- Resolved the netcdf file download issue 
- …

Subset panel does not update when dataset is changed within the area window Issue #971

---

data/class4.py

The calls to `_list_class4_files_slowly` in `data/class4.py` were missing the Class4 filename pattern argument from the configs, preventing the Navigator from generating new class4 pickle files. 
Just needed to add the filename pattern to the `_list_class4_files_slowly` function calls to fix pickle file generation.

Add filename pattern to _list_class4_files_slowly

---

oceannavigator/frontend/src/components/DatasetSelector.jsx
routes/api_v1_0.py

The current Ocean navigator UI, the Quiver variable plot option is only working for "Mercator" model class type dataset. For example : 
"giops_day": {
"name": "01. GIOPS 10 day Forecast 3D - LatLon",
"model_class": "Mercator"
}
or 
"cmems-global-analysis-forecast-phy-001-024_hourly": {
"name": "15. CMEMS Global Ocean PHYS Analysis (Hourly) 1/12 deg",
"model_class": "Mercator
"}
There will be ongoing work in the future so that Quiver plot can work with the other model class Like "Nemo" or "fvcom" type dataset, example: 
"riops_fc_3dps": {
"name": "06. RIOPS Forecast 3D - Polar Stereographic",
"model_class": "Nemo"
}
For the end user, it is essential to hide and restrict the selection of the quiver variables for non  "Mercator" type model class to avoid 500 (INTERNAL SERVER ERROR).  The …

Quiver variable restriction on model class

---

data/transformers/geojson.py
oceannavigator/dataset_config.py
routes/api_v1_0.py

This PR added a new feature in the quiver selection for the end user. The user now able to plot multiple quiver variables (one at a time) from the quiver selection menu. The current available quiver variables to plot are:
1. "Water Velocity" ("magwatervel") 
2. "Sea Ice Velocity" ("magicevel")
There was only one variable which is "Water Velocity" ("magwatervel") was available to plot in the quiver variable selection option. This PR made the option available to add more quiver variables if required for the end user.
#Changes Made in the Config File:
- In the datasetconfig.json file ([Add "bearing_component" in "magwatervel" variable component for multiple quiver variable options in UI #38](https://github.com/DFO-Ocean-Navigator/configurations/pull/38)), a component name "bearing_component" …

Add "bearing component" in "magwatervel" variable component for multiple quiver variable options in UI

---

plotting/plotter.py

Some plots are failing during the stats calculation because the selected point/line/area and variable combination contains no data. Generally this only occurs when a user selects and AOI over land but in some scenarios this may prevent a valid plot from being produced. For example, if a user selects multiple variables and one of them is empty for the AOI. This should result in the affected variable plot returning without data but currently causes the query to fail. We just need a simple check to ensure that the plot contains valid data before trying to produce statistics for the plot
Checking if the data is empty ensures that the stats calculation will succeed.  If the plot data is empty then the `get_stats_str` function will return an empty string. Something like this should of been …

Ensure plot contains data before calculating stats

---

plotting/utils.py

It appears that users have not been able to produce a transect plot from entered coordinates since we migrated to Cartopy. The issue stems from defining the map portion of the transect plot. Initially we calculated the central longitude of the map by taking the mean of the longitude portion of transect coordinates. However, this did not select the exact centre of the line/resulting plot area and resulted in Cartopy trying to draw outside the map boundaries. If we just calculate the mean using the max/min longitudes instead we get a better approximation of the map's central longitude and Cartopy is able to draw all the necessary features within the map boundary.
By only using the latitude's extremities we can centre the map plot more accurately with less work.

Fix transect plotting from entered coordinates

---

plotting/scriptGenerator.py
plotting/templates/rSUBSETtemplate.txt

The API R Script for downloading subset variables time series .nc data  was not implemented in the present Ocean navigator UI. This PR added the rSUBSETtemplate.txt for R template to download subset variables .nc data.
The client requested to implement the API R script fo subset variables. 
```sh
```

API Script R Subset Implementation- The Process Of FastAPI Migration

---

config/conda/environment.yml
config/conda/navigator-spec-file.txt
plotting/map.py

The basemap maskocean function is redundant in map.py file when plotting any selected area.  The maskocean of Add Arrow Function or add Additional Contour Plot option in the plot area also redundant. 
In the process of FastAPI migration cleanup we need to remove or replace basemap import because it was causing issue when we were trying to update Python Version to 3.10.
Basemap is deprecated in favor of the [Cartopy project](http://scitools.org.uk/cartopy/). We are replacing basemap with cartopy 
when possible.
```sh
```

Remove Basemap MaskOcean from UI

---

plotting/map.py

The Additional Contours plot in the area plot window was showing error in the backend. 
This PR resolved the below issue:
Additional contour plot not working in the area plot window #1055
##
Checks
```sh
```

Additional contour plot issue resolved

---

oceannavigator/frontend/src/components/AreaWindow.jsx
oceannavigator/frontend/src/components/Class4Window.jsx
oceannavigator/frontend/src/components/ContourSelector.jsx
oceannavigator/frontend/src/components/LineWindow.jsx
oceannavigator/frontend/src/components/MapInputs.jsx
oceannavigator/frontend/src/components/Options.jsx
oceannavigator/frontend/src/components/PointWindow.jsx
oceannavigator/frontend/src/components/SubsetPanel.jsx
oceannavigator/frontend/src/components/TrackWindow.jsx
oceannavigator/frontend/src/components/VelocitySelector.jsx
oceannavigator/frontend/src/components/lib/CheckBox.jsx

Rename Old Selecbox React Component to CheckBox component and Move  that component file to lib folder and made associated changes required to use that component.
The use Old SelecBox was used mainly to check the parameters. So the naming was misleading. As part of FAST API migration clean up process we have decided to rename the old SelecBox to CheckBox.
```sh
```

Rename Old Selecbox React Component->CheckBox and Move >lib folder

---

scripts/pregen_tiles.py
scripts/profiling_scripts/api_profiling_driver.py

Requests made using Python's requests module in pregen_tiles and other scripts have been encountering an error since SSL certs were added to the Naivgator. Setting `verify=false` will let the requests function skip SSL verification and allow the scripts to run without issue.

Disable SSL verification in python scripts

---

kml
oceannavigator/frontend/package.json
oceannavigator/frontend/src/components/MapToolbar.jsx
oceannavigator/frontend/yarn.lock

Users can currently scroll through the class4 calendars indefinitely. Since we have a limited range of class 4 data available, date ranges limits were added to prevent users from scrolling past the available data. The ranges are:
Ocean Predict
- Jan 2019 - Feb 2022
RIOPS Assimilated Observations
- Feb 2022  - May 2022
The jQuery datepicker provides arguments to specify max and min dates, we just need to provide date ranges.
The max date limit will be removed once new Class4 data becomes available.

Limit the date ranges of class4 calendars

---

routes/api_v1_0.py
routes/schemas/__init__.py
routes/schemas/timedimension_schema.py

Add time dim unit API endpoint.
api/v1.0/timeunit/?dataset=????
Finds "time_dim_units" associated with a dataset
Example: 
Query : http://navigator.oceansdata.ca/api/v1.0/timeunit/?dataset=giops_day
Will return time_dim_unit of "GIOPS 10 day Forecast 3D - LatLon" dataset which is "seconds since 1950-01-01 00:00:00"
Client requested to implement time dimension unit API endpoint
```sh
```

Add time dim unit API endpoint or add to dataset payload

---

data/observational/__init__.py

It looks like MySQL closes all database connections after some period of inactivity which is causing issues for the Obs functions. In the past the Flask-SQLAlchemy library had a built in mechanism to keep connections alive but since we've migrated to FastAPI we need to recycle the connection pool. See https://sentry.io/organizations/dfo-ocean-navigator/issues/3739259890/?project=5511557&query=is%3Aunresolved&referrer=issue-stream for an example of this error. 
MySQL closes connections after 8 hours, by setting `pool_recycle=3600` we ensure that there's always a connection available.

Fix 'MySQL server has gone away' error with pool recycling

---

oceannavigator/dataset_config.py
oceannavigator/frontend/src/components/DatasetSelector.jsx
routes/api_v2_0.py
tests/test_api_v_2_0.py
tests/test_dataset_config.py
tests/testdata/datasetconfigpatch.json

The Navigator currently uses the names of variables names to determine whether or not they can be used as vector variables. If a variable's name contains both "mag" and "vel" it is categorized as such. This has worked well before but now that we'd like to pull data from our THREDDS server we may not have control over the names of variables.  Instead, a `vector_variable` attribute will be added to datasets in datasetconfig.json which will list the variables which can be used to plot quivers. 
This gives us more flexibility in choosing which variables to display as vectors.

Specify quiver variables in datasetconfig

---

oceannavigator/frontend/src/components/DatasetSelector.jsx
routes/api_v2_0.py
tests/test_api_v_2_0.py

The `/range` API endpoint was missed during the FastAPI migration and the query path was not properly defined which broke the "Auto" button in the dataset selector. This PR provides the full endpoint path which restores the "Auto" button functionality.
The endpoint requires the complete query path to work.

Fix /range API endpoint

---

data/calculated_parser/lexer.py
data/transformers/geojson.py
oceannavigator/frontend/src/components/Map.jsx
oceannavigator/frontend/src/images/s111/I0.svg
oceannavigator/frontend/src/images/s111/I1.svg
oceannavigator/frontend/src/images/s111/I2.svg
oceannavigator/frontend/src/images/s111/I3.svg
oceannavigator/frontend/src/images/s111/I4.svg
oceannavigator/frontend/src/images/s111/I5.svg
oceannavigator/frontend/src/images/s111/I6.svg
oceannavigator/frontend/src/images/s111/I7.svg
oceannavigator/frontend/src/images/s111/I8.svg
oceannavigator/frontend/src/images/s111/I9.svg
routes/api_v2_0.py
tests/data/transformers/test_geojson.py

There are a few final issues that need to be fixed before we can use GDWPS variables to plot quivers:
1. GDWPS variables from THREDDS include "-" characters which were interpreted as subtraction by the calculated parser. 
This can be resolved by allowing hyphens to pass the regex filter when defining ID tokens in the calculated parser. This does not affect other calculated variable equations that use subtraction operations. 
2. The wave direction variables are given as a bearing only and should be plotted as quivers of uniform size, i.e. no magnitude.
Because we now specify the bearing component in magnitude variables and explicitly list vector variables we can check to see if quiver variables have a 'bearing_componet' attribute in the '/data' endpoint. If not `bearing` is omitted from …

Plot GDWPS Quivers

---

oceannavigator/frontend/src/components/MapToolbar.jsx
oceannavigator/frontend/src/components/OceanNavigator.jsx
oceannavigator/frontend/src/components/WarningBar.jsx

In #1052 the date ranges of both Class4 calendars were limited as the class4 data pipeline had stopped. Now that Class4 production has resumed this PR removes the hardcoded date range and replaces it with a range pulled from the list of available Class4 data. The warning banner has also been removed since it is no longer relevant. 
Dynamically setting the date range will keep the calendars in sync with the available Class4 data.

Set class4 calendar range using available data

---

oceannavigator/frontend/src/components/AxisRange.jsx
oceannavigator/frontend/src/components/DatasetSelector.jsx
oceannavigator/frontend/src/components/PlotImage.jsx
oceannavigator/frontend/src/components/PointWindow.jsx
plotting/plotter.py
plotting/profile.py
plotting/sound.py
plotting/timeseries.py

This PR adds variable range controls to the point window per user requests. A new `AxisRange` component which allows users to set a specified range for the plot axis range. By default these ranges are set to the values specified within the datasetconfig.json file but the provided controls include a reset button and an _Auto_ option. This component adds the range values to the plot query, if _Auto_ is checked or values are not provided in the query the backend will select the appropriate axis range as before.
The `AxisRange` component is based on the `Range` component which is used to specify the colorscale on the main map. The functionality needed is similar to the colormap range selector but there were a few important differences that necessitated a new component.

Add axis range controls to profile plots

---

oceannavigator/frontend/src/components/MainMap.jsx

I noticed that displayed quiver arrows were not changing when the dataset changed. This is because the `useEffect` hook which used to display them was only called when changing to the quiver variable itself and since we're only displaying quiver arrows for `magwatervel` it never updates. Adding the dataset id to the useEffect dependencies fixes the problem.
Only way since were using useEffect to trigger quiver arrows.

Update quiver arrows when dataset changes

---

data/netcdf_data.py
data/utils.py
oceannavigator/frontend/src/components/DatasetSelector.jsx
oceannavigator/frontend/src/components/SubsetPanel.jsx
oceannavigator/frontend/src/components/TimePicker.jsx

Users notified us of an issue causing the Navigator to crash when trying to make an area plot with an older timestamp from a historical dataset. It turned out that there were several small issues contributing to the crash:
1. Selecting a timestamp older than the current `dataset.starttime` value breaks the `DailyCalendar` component. 
When selecting a dataset with many timestamp options the DatasetSelector component sets the `dataset.starttime` value to the 20th most recent value to prevent overly long timeseries queries. However, this value does not get updated if the user selects a timestamp before it. This results in the start and end time calendar components breaking because the start time value is outside of the expected date range. To resolve this a `changeTime` method was added  to …

Fix subset panel and related timepicker bugs

---

.gitignore
config/conda/environment.yml
oceannavigator/frontend/src/components/TimeSlider.jsx
oceannavigator/frontend/src/components/TimeSliderButton.jsx
oceannavigator/frontend/src/stylesheets/components/_TimeSlider.scss

Additional buttons are added to allow users to quickly jump to the beginning and end of the time slider. In addition to this functionality tooltips have been added to provide feedback on what dates are available outside of the currently displayed time range.

Add beginning and ending time buttons to Timeslider component

---

oceannavigator/dataset_config.py
oceannavigator/frontend/src/components/DatasetSelector.jsx
oceannavigator/frontend/src/components/MainMap.jsx
routes/api_v2_0.py
tests/test_api_v_2_0.py

This work allows the navigator to pan to a specific location and zoom level when the dataset is changed. To do so a `default_location` variable specifying the coordinates and zoom level needs to be added to the dataset entry in the datasetconfig.json file. This variable should be in the format `[lon, lat, zoom]`. This data is included in the `/datasets` API response and appended to the dataset object created by the DatasetSelector component. When the user selects a new dataset and clicks go an effect in the `MainMap` component checks the dataset object for the `default_location` variable. If present, a new OpenLayers view object is created with these coordinates and zoom level which causes the map to pan to the location. If this variable is not defined in the dataset config the map's …

Pan main map to dataset location on change

---

oceannavigator/frontend/src/stylesheets/components/_AreaWindow.scss
oceannavigator/frontend/src/stylesheets/components/_DatasetSelector.scss

"GO" button in all plot windows was not properly aligned. Now it is displaying evenly in all plot windows.
Changes made in css.
```sh
```

Changes fixed for 'Go' button in plot windows, is now displaying correct.

---

oceannavigator/frontend/src/stylesheets/components/_SelectBox.scss

Fixed Dataset dropdown overlaps “variables” label on dataset selector for some datasets. Now it is not overlapping for any of the dataset dropdown
Since dataset dropdown was overlapping on “variables” label, I did some changes in CSS styling to fix it. 
```sh
```

Fixed Dataset dropdown overlaps “variables” label

---

oceannavigator/frontend/src/components/LineWindow.jsx
oceannavigator/frontend/src/components/NumberBox.jsx

It looks like the Linear Threshold feature was broken during the UI updated (v9.0). The issues appears to lie within the _NumberBox_ component where two problems occur: the underlying `<input>`'s event was passed to the `this.changed` event handler instead of just the event value and there was no validation in place to ensure that the received value was a number. 
To restore functionality we now just pass the event's value to the input change handler and added validation to ensure that this is a number. 
Following best practices for a numeric input in React.
Fixed some code formatting in _LineWindow_ and _NumberBox_ components.

Fix Linear Threshold feature

---

data/netcdf_data.py

Norm notified us of an issue encountered when subsetting an area with NetCDF3 NC format. The subset request fails and returns  a "daemonic processes are not allowed to have children" error message from the multiprocessing library. The cause of this error appears to be the _nprocs_ argument passed to the `pyresample.kd_tree.resample_nearest` function triggering the use of multiprocessing to handle the resampling operation which raises the error. Removing this argument fixes the issue but may lead to a performance hit on large resampling operations though this has not been an noticeable during testing. 
Async operations cannot spawn child operations so removing the _nprocs_ argument is the most direct way to fix this issue.

Fix NetCDF3 NC Subsetting

---

oceannavigator/frontend/src/components/DatasetSelector.jsx
oceannavigator/frontend/src/components/MainMap.jsx
oceannavigator/frontend/src/components/MapInputs.jsx
oceannavigator/frontend/src/components/OceanNavigator.jsx
oceannavigator/frontend/src/stylesheets/components/_MapInputs.scss
oceannavigator/translations/fr.json

We received a request to provide a way to hide the data layer so that users can view the bathymetry below. A practical solution was to add a _Hide Data Layer_ button to the MapInputs panel which toggles the data layer's visibility in the MainMap component via the `mapSettings` prop.
This is a intuitive way to allow users to hide the data layer and was straightforward to implement. 
The button currently only toggles the data layer. Other layers, such as drawing layers, quivers, and observations, can easily be added to this functionality if requested.

Add Hide Data Layer button to MapInputs panel

---

config/conda/environment.yml
config/conda/navigator-spec-file.txt
data/calculated_parser/functions.py
plotting/sound.py
plotting/ts.py
scripts/data_importers/argo.py
scripts/data_importers/glider.py
scripts/data_importers/nafc_ctd.py
scripts/data_importers/seal.py
scripts/pfile.py

seawater package is deprecated. Replaced with gsw
gsw uses the TEOS-10 instead of the EOS-80 used by 'seawater' which is now considered obsolete
tempgradient() function now returns result in K/Pa rather than C/db. This change needs to be reflected in configs branch
```sh
```

Seawater to gsw

---

plotting/utils.py

Since updating to Python 3.12 I noticed that the _Auto_ function on the colormap range selector was not updating the range values when clicked. The query returns error 500.  This was due to the endpoint returning numpy.float64 type values which are not compatible with json. To fix the problem the `normalize_scale` function casts the min and max values of the data array to regular python floats. 
Castling This ensures that the return values are json compatible and does not affect their values.

Fix Colormap Range "Auto" Function

---

oceannavigator/frontend/src/components/EnterCoordsWindow.jsx

The coordinate fields in the `EnterCoordsWindow` caused the Navigator to crash when the values were deleted. To resolved we added some additional input validation before updating the `vectorCoords` prop to avoid the crash.
This approach ensures that valid values are passed to the `vectorCoords` prop which is mapped to the input fields.

Fix EnterCoordsWindow crash

---

oceannavigator/frontend/src/components/ComboBox.jsx

Issue #1105 . While dataset is loading the values are set to null which causes a crash on update.
I edited the ComboBox.js file to skip the update if the values from 'dataset0' are null. This will skip the updates that happen while the dataset is loading. 
```sh
```

area plot crash fix

---

data/netcdf_data.py

VM/Timeseries plot requests covering more than ~50 timestamps have historically taken longer than the 5 minute response time limit allotted to Navigator queries. In the past we have limited the timepicker components so that users cannot select timespans greater than 50 timestamps but this was dropped when the UI was refactored last year. Instead of taking a similar approach I opted to subsample the timestamps so than users can request timeseries plots over any length of time but the result plot will only have a maximum of 50 points.    
Unlike the previous approach described above, this allows users to plot any length of timeseries.

Limit points in timeseries plot

---

data/netcdf_data.py

#1106 
Taking all 4 corners allows for proper slicing despite RIOPS' irregular grid
Depending on location, subset may have rotated orientation however the data is correct
Selected area:
Before:
After:
```sh
```

fixed slicing for netcdf subset

---

oceannavigator/frontend/src/stylesheets/components/_DatasetDropdown.scss

#1123 
Added 'flex: 1' so that the dataset dropdown div covered the area of it's child components. However this caused the dropdown icon to overlap so I adjusted the 'dd-toggle-caret' style as well.
Not sure if the edits to 'dd-toggle-caret' look bad elsewhere but couldn't find any issues myself
```sh
```

'Dataset Dropdown covers Variable Selector for some datasets' fix

---

oceannavigator/frontend/src/components/DatasetSelector.jsx

on #1116 I overlooked including quiver when updating the map from mountedDataset. Added now so that "Get Link" will include state of quiverVariable and quiverDensity
Copied the process used for the other variables in moountedDataset
```sh
```

include quiver when updating map from mountedDataset

---

oceannavigator/frontend/src/components/AreaWindow.jsx
oceannavigator/frontend/src/components/ColormapRange.jsx
oceannavigator/frontend/src/stylesheets/components/_ColormapRange.scss

#1135 
I decided to use the existing ColormapRange component to avoid redundancy. 
I'm not sure why the check box isn't in line with the other ones in the area settings card.
```sh
```

Add scale selector to AreaWindow

---

data/calculated_parser/functions.py

Received a request to add a Water Density variable to the Navigator (see [Issue #1147](https://github.com/DFO-Ocean-Navigator/Ocean-Data-Map-Project/issues/1147)). A density function has already been implemented in `data/calculated_parser/functions.py` but the pressure values needed to be padded so that they could be broadcast against salinity and temperature to calculate the sea water density. For this I used the same approach as other calculated variables such as sound speed. 
Same approach has been used in other calculated variable functions and has been shown to work.

Fix Density variable calculation

---

oceannavigator/__init__.py
oceannavigator/frontend/src/components/PlotImage.jsx
plotting/plotter.py
plotting/profile.py
plotting/timeseries.py
plotting/utils.py
routes/api_v2_0.py

We received a request to add a NetCDF file output option to the point plotters (see issue #1150). A _NetCDF_ button was added to the save image menu and related functionality added to the profiler and timeseries plotters. This feature should produce NetCDF files for any profile or VM plot regardless of the number of variables, points, and depths present in the current plot and the output will always contain the standard time, depth, lat, lon dimensions. 
Rather than recreate the subset window from the area plotter we decided that this should be a quick to use feature that allows users to quickly download the data visible in the current plot.

Add NetCDF option to Profile and Virtual Morning Save Image menu

---

oceannavigator/frontend/index.html

Adds a link to the Ocean Navigator Lite (https://lite.oceannavigator.ca) to the landing page for quick access. Removed the `Open Ocean Navigator` link to minimize redundancy and clutter.

Add ONav Lite link to landing page

---

data/observational/orm/station.py
oceannavigator/frontend/src/components/ObservationSelector.jsx
oceannavigator/frontend/src/components/TrackWindow.jsx
plotting/track.py
routes/api_v2_0.py

This PR address a number of issues in the observation point, track, and plot endpoints:
- The ORM range of lat and lon coordinates does not account for wrapping value in a continuous line.
- The track variable value in the query may be a list or single value so logic was added to the track plotter to accommodate these datatypes.
- The query string format separated variables with `;` which prevented the query from reaching the end point. This has been replaced with `&` as commonly used to separate variables in query strings.

Fix obs point, track, and plot endpoint issues

---

oceannavigator/frontend/src/components/AreaWindow.jsx
plotting/map.py

We were notified of an issue that prevented area plots below -30 degrees latitude. After some digging I found that the Lambert Conformal projection used in the area plotter for areas within (-85, 85) deg latitude does not extend beyond this range. Switching to the Mercator projection allows all plots within this range. While testing I also found that the area boundary is not properly calculated for polar plots outside of this range, especially when the area intersected the north/south pole. To resolve this I opted to re-calculate the bounds and centroid in the plots own CRS to ensure that the plot was centered on the polygon.
Adopting the Mercator projection allows us to use the majority of the globe for standard plots. 
Comparisons of plots before/after changes:
_Hint_ To run all python …

Fix projection in area plots

---

oceannavigator/frontend/src/components/SubsetPanel.jsx

The subset panel API query did not match the update API query format that was introduced when the Navigator migrated to FastAPI. This updates the query to the current query format so that the API Script option is now functional.

Fix subset panel API query

---

oceannavigator/frontend/src/components/OceanNavigator.jsx
oceannavigator/frontend/src/components/map/Map.jsx

The OpenLayers select feature inherently allows users to select multiple features by holding the shift key when clicking on them. The `Map` component however fires the signal to open the plot window immediately after a selection is made preventing users from easily selecting multiple points to plot. A shift key check is added to the select function to signal that the user is selecting multiple points prevents the window from opening via a `multiSelect` state variable. Likewise, an event listener is added to the main ocean navigator component to check that the shift key is released which modifies the `multiSelect` state and allows the plot window to open.
These checks allow the navigator to track when the user is selecting multiple points and delay the opening of the plot window.
Multiple …

Allow multiple point selection with shift key

---

oceannavigator/frontend/src/components/Map/Map.jsx

During release testing I found a bug that prevented plotting of line and area features created from combining point features. The root of the issue is that the previous selected features were not cleared from the Select interaction after they had been removed from the vector layer resulting in the Navigator adding a string of _NaNs_ to the feature coordinates. Clearing the select interaction before adding the combined point feature to it resolves the issue.

Fix "combine point features" bug in Map component 

---

data/netcdf_data.py

Users requiring NC3 Classic formatted subsets have reported issues with the fill value when importing the NC file into other legacy software. This PR changes the fill values to 9999 for NC3 Classic subsets to ensure compatibility without affecting other uses.

Change fill value for NC3 subset output

---

data/mercator.py
data/nemo.py
oceannavigator/__init__.py
plotting/class4.py
plotting/hovmoller.py
plotting/line.py
plotting/sound.py
plotting/stats.py
plotting/stick.py
plotting/transect.py
plotting/ts.py
scripts/apply_mask.py
scripts/drifter_process.py
scripts/get_drifters.py
scripts/readNovaFloat_SN472.py
scripts/usingFloat2extracCls4.py
tests/test_colormap.py
tests/test_data_class4.py
tests/test_netcdf_data.py
tests/test_scriptGen.py

I wanted to look at some of the scripts but I did not want to install python2.  Then I ran `black .` and that changed other files.
This was the least invasive approach.  converting more of these strings to f-strings would be better but I am not sure what the code style is for this repo.
The changes outside of scripts were auto formats by black.
I went to run the unit tests and I got this far down the dependencies before giving up.
`pip install xarray ply fastapi metpy flask dask sentry_sdk gsw pyinstrument geopy pyresample pydantic_settings babel views` 
Do you have a requirements file?

Make prints in scripts python3 compatible

---

data/netcdf_data.py

Previously, the longitude values in the dataset ranged from 0° to 360°, which caused issues when selecting regions that crossed the dateline (180°). As a result, when users plotted areas near the border (e.g., across ±180°), the subsetting logic failed and returned data for the entire globe instead of just the selected region
This pull request fixes those issues by:
Normalizing longitudes to -180° to 180°
Correctly identifying and slicing the region, even if it crosses the antimeridian
Ensuring the output NetCDF file reflects only the requested area
```sh
```

Wrap subsets that cross 0° and set output longitude range to -180° to 180° 

---

oceannavigator/frontend/src/components/Map/Map.jsx
oceannavigator/frontend/src/components/Map/utils.js

#1195 
Zoom level 8 returns empty topographic basemap tiles , because of the transition from topography tiles to mbt tiles.Fixed logic for a smoother transition and no more empty tile is returned.
```sh
```

added a smooth transition at zoom level 7

---

plotting/map.py

Changes in #1220 cleaned up code responsible for drawing the land geometries and instead opted to use Cartopy's native features to handle land geometries. It turns out however that these methods were actually more inefficient in our production environment due to  changes made to _PyProj_ and area plots would then take up to two minutes to be rendered. To restore performance we restored the geometry filtering used prior to the above changes that minimizes the number of objects that needs to be transformed and drawn in the plot's projection. 
Cartopy's feature interfaces includes a number of methods to filter geometries based on the plot extent. I tested all of the available options along with adding them as features vs geometries however none of these approaches were able to produce plots …

Improve drawing of land geometries in area plots

---

oceannavigator/frontend/src/components/DatasetSelector.jsx

The `DatasetSelector` component was storing the map's settings as another state variable but they are never used within it. Recent changes to the component tried to maintain and manage that data but it led to bugs. This PR removes the mapSettings data and other related but unused variables such as `DATASET_DEFAULTS` and `MAP_DEFAULTS`. 
The data was unused and the component needed some cleaning up.

Remove mapSettings from DatasetSelector component

---

data/netcdf_data.py

When testing v9.6.2-rc0 we found that the subset function was broken because the wrong variables were being selected as the datasets dimensions. It turns out that in current versions of xarray the output of `xarray.Dataset.variables.keys()` is now sorted alphabetically and the `latitude_longitude` variable in datasets was getting assigned to lat_var/lon_var selected instead of the correct dimensions.  Instead of taking this approach we will now pull the correct variable names from the dataset's config object. 
Using the lat/lon variable names provided in the dataset config object ensures that the correct variables will always be selected.

Fix lat lon variable selection in subset function 

---

data/netcdf_data.py
data/sqlite_database.py
routes/api_v2_0.py
tests/test_sqlite_database.py

Added a function to get all dataset timestamps from the dataset's sqlite3 database. This will be useful in upcoming features where we'll need to filter datasets by available datetimes. 
Quickest way to get the available timestamps. We tried filtering using a variable key but the joins made the feature too slow to be practical.

Get all timestamps from dataset dbs
