DFO-Ocean-Navigator/Ocean-Data-Map-Project

.gitignore, oceannavigator/frontend/src/components/ImageSize.jsx, oceannavigator/frontend/src/components/LineWindow.jsx, oceannavigator/frontend/src/components/OceanNavigator.jsx, oceannavigator/frontend/src/components/PlotImage.jsx, plotting/hovmoller.py, plotting/plotter.py, plotting/transect.py
Reverts DFO-Ocean-Navigator/Ocean-Data-Map-Project#69
=> Revert "Fixed Hovmoller start time not updating plotted image."

oceannavigator/frontend/src/components/AreaWindow.jsx, oceannavigator/frontend/src/components/Class4Window.jsx, oceannavigator/frontend/src/components/ComboBox.jsx, oceannavigator/frontend/src/components/ContinousTimePicker.jsx, oceannavigator/frontend/src/components/ContourSelector.jsx, oceannavigator/frontend/src/components/DatasetSelector.jsx, oceannavigator/frontend/src/components/DepthLimit.jsx, oceannavigator/frontend/src/components/DrifterSelector.jsx, oceannavigator/frontend/src/components/DrifterWindow.jsx, oceannavigator/frontend/src/components/EnterArea.jsx, oceannavigator/frontend/src/components/LineWindow.jsx, oceannavigator/frontend/src/components/LocationInput.jsx, oceannavigator/frontend/src/components/MapInputs.jsx, oceannavigator/frontend/src/components/MapToolbar.jsx, oceannavigator/frontend/src/components/NumberBox.jsx, oceannavigator/frontend/src/components/ObservationSelector.jsx, oceannavigator/frontend/src/components/OceanNavigator.jsx, oceannavigator/frontend/src/components/Permalink.jsx, oceannavigator/frontend/src/components/PlotImage.jsx, oceannavigator/frontend/src/components/PointWindow.jsx, oceannavigator/frontend/src/components/Range.jsx, oceannavigator/frontend/src/components/SelectBox.jsx, oceannavigator/frontend/src/components/TimePicker.jsx
* All components now bind relevant functions in their c-tors for better performance.
* Fixed a yet-again broken copy button.
=> Optimization pass + bugfix.

oceannavigator/frontend/src/components/AreaWindow.jsx, oceannavigator/frontend/src/components/Class4Window.jsx, oceannavigator/frontend/src/components/ComboBox.jsx, oceannavigator/frontend/src/components/ContinousTimePicker.jsx, oceannavigator/frontend/src/components/ContourSelector.jsx, oceannavigator/frontend/src/components/DatasetSelector.jsx, oceannavigator/frontend/src/components/DepthLimit.jsx, oceannavigator/frontend/src/components/DrifterSelector.jsx, oceannavigator/frontend/src/components/DrifterWindow.jsx, oceannavigator/frontend/src/components/EnterArea.jsx, oceannavigator/frontend/src/components/LineWindow.jsx, oceannavigator/frontend/src/components/LocationInput.jsx, oceannavigator/frontend/src/components/MapInputs.jsx, oceannavigator/frontend/src/components/MapToolbar.jsx, oceannavigator/frontend/src/components/NumberBox.jsx, oceannavigator/frontend/src/components/ObservationSelector.jsx, oceannavigator/frontend/src/components/OceanNavigator.jsx, oceannavigator/frontend/src/components/Permalink.jsx, oceannavigator/frontend/src/components/PlotImage.jsx, oceannavigator/frontend/src/components/PointWindow.jsx, oceannavigator/frontend/src/components/Range.jsx, oceannavigator/frontend/src/components/SelectBox.jsx, oceannavigator/frontend/src/components/TimePicker.jsx
* Variable scale now keeps user-defined values when changing date/variable/dataset. Default and Auto buttons remain unchanged.
* Increased range selector precision to 4 decimal places from 3.
=> Bugfix: Fixed variable scale not keeping user-defined values.

oceannavigator/frontend/src/components/AreaWindow.jsx, oceannavigator/frontend/src/components/Class4Window.jsx, oceannavigator/frontend/src/components/CoordInputPanel.jsx, oceannavigator/frontend/src/components/EnterArea.jsx, oceannavigator/frontend/src/components/LineWindow.jsx, oceannavigator/frontend/src/components/PointWindow.jsx, plotting/map.py
Users have requested to have the bearing information included in the CSV output.
=> Add bearing information to CSV export when quiver data is displayed.

oceannavigator/frontend/index.html
=> Reverted landing page to "bland style".

oceannavigator/frontend/src/components/DatasetSelector.jsx, scripts/drifter_process.py
Quick bug fix for the drifter files to make them update again (they stopped on the 14th) issue #150
added change display to indicate time is in UTC #149
=> Bug fix drifters

oceannavigator/frontend/index.html, oceannavigator/frontend/src/components/AreaWindow.jsx
* added some SEO improvements to the landing page. issue #41 and #8 
* fixed area plot bug #156 
this should be released as version v2.2.2
=> SEO update and plot bug fix

oceannavigator/frontend/src/components/LineWindow.jsx, oceannavigator/frontend/src/components/PlotImage.jsx, plotting/hovmoller.py, plotting/plotter.py, plotting/sound.py, plotting/stick.py, plotting/timeseries.py, plotting/transect.py
* Works for transects and hovmoller diagram
=> Added colourmap dropdown to Line Window, and .csv fix.

oceannavigator/frontend/src/components/OceanNavigator.jsx, oceannavigator/frontend/src/components/warning.jsx, oceannavigator/frontend/src/stylesheets/components/_MapToolbar.scss
This includes a warning bar about how the water velocity is wrong. It will need to be changed to not show the bar when there are not critical bugs that we need to inform people about. This should be changeding the "show: true" to "show: false" in "warning.jsx"
=> Added warning bar about bugs

oceannavigator/frontend/src/components/TimePicker.jsx, oceannavigator/views.py
* Forgot about the custom JSON encoder in views.py when I was making some changes.
Pretty sure that's record time for a bugfix haha :stuck_out_tongue_closed_eyes:
=> Fixed broken RIOPS

oceannavigator/frontend/src/components/StatsTable.jsx, plotting/basemap.py, plotting/map.py, plotting/stats.py
These changes have fixes for:
* Very Large area plots fail #234
* stats tab not forking for plots across the dateline #236 
* plots crossing the dateline failing #130 
* Area plot near poles does not display properly #132
It also includes improvements for:
* Rendering large plots by rending the in Mercator projection.
* Area plot box colours now are black with white borders for better visibility on all colours.
=> World wrap fixes

plotting/stats.py
I don't have a good way to computer the median when crossing the date line so for the time beaing we will just let the use know we can't get that
=> don't compute median

oceannavigator/frontend/src/components/AreaWindow.jsx, oceannavigator/frontend/src/components/CustomPlotLabels.jsx, oceannavigator/frontend/src/components/PlotImage.jsx, plotting/map.py, plotting/plotter.py
Added custom plot titles option in Area Window
=> Custom plot title(area)

data/netcdf_data.py, oceannavigator/frontend/src/components/AreaWindow.jsx, oceannavigator/frontend/src/components/CustomPlotLabels.jsx, oceannavigator/views.py, runserver.sh
=> Implemented Netcdf NC export for GIOPS Daily

oceannavigator/frontend/src/components/PlotImage.jsx, plotting/scriptGenerator.py, routes/api_v0_0.py
-Updated script generations for python
-Updated R generator to use date instead of index
-Changed python to python3 for script button
=> API Update

Jenkinsfile, data/fvcom.py, tests/test_fvcom.py, tests/test_merc.py, tests/test_nemo.py
* Added test_nemo.py to jenkins pipeline as well.
=> Rewrote Jenkins pipeline

plotting/scriptGenerator.py, routes/api_v1_0.py, tests/test_scriptGen.py
=> Fixed missing dot in script outputs

oceannavigator/frontend/src/components/AreaWindow.jsx, oceannavigator/frontend/src/components/LineWindow.jsx, oceannavigator/frontend/src/components/Map.jsx, oceannavigator/frontend/src/components/MapToolbar.jsx, oceannavigator/frontend/src/components/OceanNavigator.jsx, oceannavigator/frontend/src/components/PointWindow.jsx, oceannavigator/frontend/src/components/Range.jsx
Now enables when making points lines or areas,
and disables when the reset button is hit
=> Fixed Plot Button

oceannavigator/frontend/src/components/AreaWindow.jsx
* Fixed name mismatch in subsetArea function binding.
* Should fix the subset button doing nothing.
=> Weekly Update

plotting/scriptGenerator.py
the URL needed to be encoded to allow of all requests to be understood.
=> fix for bug #342 broken R script

routes/routes_impl.py
Wrapped the map so when the longitude is smaller than -180 or larger than 180 it will convert it to a value within those bounds.
=> Fixed malformed or Inaccessible DAP

oceannavigator/frontend/src/components/Map.jsx, oceannavigator/frontend/src/components/MapToolbar.jsx
Upload CSV fixed for point, line, and area plots.
=> Upload CSV Fix

oceannavigator/frontend/src/components/OceanNavigator.jsx
Velocity representation fixed in #378
=> Removed warning banner.

data/netcdf_data.py, oceannavigator/frontend/src/components/IceLayer.jsx, oceannavigator/frontend/src/components/Layer.jsx, oceannavigator/frontend/src/components/LayerSelection.jsx, oceannavigator/frontend/src/components/OceanNavigator.jsx, oceannavigator/frontend/src/components/TimeBarContainer.jsx, oceannavigator/frontend/src/components/TimeSelect.jsx, oceannavigator/frontend/src/stylesheets/components/_MapInputs.scss, oceannavigator/frontend/src/stylesheets/components/_OceanNavigator.scss, plotting/tile.py
Wind needs to be fixed, and wind barbs validated before we allow this option.
=> Fixed, then disabled wind barbs

.github/release-drafter.yml
Adding Release Drafter bot to help with our changelog: https://probot.github.io/apps/release-drafter/
=> Add Probot Release Drafter

.github/config.yml
https://github.com/apps/request-info
No more empty descriptions.
=> Add needs-more-info probot

oceannavigator/frontend/src/components/AreaWindow.jsx, oceannavigator/frontend/src/components/ComboBox.jsx, oceannavigator/frontend/src/components/CoordInputPanel.jsx, oceannavigator/frontend/src/components/DrifterSelector.jsx, oceannavigator/frontend/src/components/EnterLine.jsx, oceannavigator/frontend/src/components/Map.jsx, oceannavigator/frontend/src/components/MapToolbar.jsx, oceannavigator/frontend/src/components/OceanNavigator.jsx, oceannavigator/frontend/src/components/Options.jsx, oceannavigator/frontend/src/components/Permalink.jsx, oceannavigator/frontend/src/components/Range.jsx, oceannavigator/frontend/src/components/TimePicker.jsx, oceannavigator/frontend/src/i18n.js, oceannavigator/frontend/src/index.jsx
Cleaning up jsx files by running `eslint --ext .jsx,.js src/ --fix`
There's about 100 still to be fixed manually
There's only one way.
Code quality should be more of a priority in the future.
=> eslint auto-fixes 

data/mercator.py, data/netcdf_data.py, plotting/hovmoller.py, plotting/utils.py, tests/test_merc.py, tests/test_nemo.py
* The `plotting/utils.py` had some functions that were duplicated in the `data` package so I opted to dump the former and re-factor the latter.
* Removed a couple of unused functions and function calls.
* Sorted import statements for modified files.
* Added new tests :tada: 
* Added more docstrings :tada: 
I ran all the working unit tests and everything passed that was supposed to pass.
=> Small refactor

scripts/readNovaFloat_SN472.py, scripts/usingFloat2extracCls4.py
Un-edited scripts from Jinshan.
* Extracts Argo floats from class4 files.
=> Add Jinshan scripts

config/conda/environment.yml
* Fix missing gdal
* Remove random pip package
=> Conda fix (#466)

config/conda/environment.yml, oceannavigator/frontend/src/components/Map.jsx, oceannavigator/frontend/src/components/PlotImage.jsx, plotting/class4.py, plotting/scriptGenerator.py
Enables class4 script generation. R Scripts are still broken (#463).
=> Band-aid fix to get class4 script gen working

data/__init__.py, data/netcdf_data.py, oceannavigator/dataset_config.py, oceannavigator/datasetconfig.json, tests/test_api_v_1_0.py, tests/test_dataset_config.py
* Giops monthly dataset only at the moment.
* We will test on wednesday
=>  Restore calculations involving angle file for GIOPS

oceannavigator/frontend/src/components/Map.jsx, oceannavigator/frontend/src/stylesheets/components/_Map.scss
Adds a slider for controlling the zoom level of the map.
I don't think these changes could possibly break anything.
=> Zoom slider

data/__init__.py, data/nemo.py, data/netcdf_data.py, data/utils.py, data/variable_list.py
Our code documentation is fairly poor at the moment, so I spent some time filling in the blanks for some classes in the `data` package.
=> Document classes in data package

oceannavigator/datasetconfig.json
Just changed some variable names in the dataset config.
Sound Channel Axis -> Deep Sound Channel Axis
Sound Channel Bottom -> Deep Sound Channel Bottom
=> Changed Sound Calc Names to add deep

data/calculated_parser/functions.py, tests/test_functions.py
Implemented Nabils unittest suggestions
=> Modify tests

oceannavigator/frontend/src/components/AreaWindow.jsx, plotting/map.py
Resolves #541 
Recently, the colormap when drawing an area map for dataset comparison was broken.
This fixes it.
Fixed Plot:
=> Colormap_diff Fix

data/calculated_parser/functions.py, oceannavigator/datasetconfig.json, plotting/timeseries.py, routes/routes_impl.py, tests/test_functions.py
This pull requests implements thresholding and greater extrema comparison to improve the accuracy of sub surface sound channels. 
In particular this PR significantly reduces false positives.
This also adds a fix to the depth excess calculation. Some coordinates were being set to random values.
=> Improved Sub-Surface Channel Detection

data/data.py, data/nemo.py, data/netcdf_data.py, plotting/timeseries.py
Fixes most of the virtual mooring problems. However, I had to plot it as points for now, because the lines weren't attached to the points in the correct order.
=> Virtual Mooring fix

data/calculated_parser/parser.py
=> Subset fix

data/calculated_parser/parser.py
* test
* test
* removed break
* test
* test
* test
=> Subset fix (#549)

oceannavigator/frontend/src/components/PlotImage.jsx, oceannavigator/frontend/src/components/PlotLabel.jsx, oceannavigator/frontend/src/components/PointWindow.jsx, oceannavigator/frontend/src/components/Scale.jsx, oceannavigator/frontend/src/stylesheets/components/_PointWindow.scss, plotting/profile.py, plotting/sound.py
This adds in the ability to specify custom x and y axis scales and labels, as well as changes the method of adding a custom plot title.
This PR also slightly rearranges the data selection layout for point plots.
=> Custom Plot Settings

plotting/map.py
Makes the bathymetry lines on the map more prominent, as well as increases the size of the bathymetry labels.
=> Bathymetry

oceannavigator/datasetconfig.json
Fixes the crashing of some datasets
=> datasetconfig.json fix

data/calculated_parser/parser.py
This fixes the Surface Dataset problem on the master branch.
The hotfix branch will fix it for v4.1.4
=> test hotfix

oceannavigator/frontend/src/components/Map.jsx, oceannavigator/frontend/src/components/MapToolbar.jsx
=> Multi point fix

oceannavigator/frontend/src/components/Layer.jsx, oceannavigator/frontend/src/stylesheets/components/_Map.scss
Sets a max width so that a layer stays on a single line. resolves #580
=> Scale bar align fix

oceannavigator/frontend/src/components/Map.jsx
You can now click on predefined points again. (And other things like class4's)
Resolves #582 
*** No picture because I can't capture an image of me clicking ***
=> Feature selection

oceannavigator/frontend/src/components/ContactButton.jsx, oceannavigator/frontend/src/components/Contacts.jsx, oceannavigator/frontend/src/components/CoordInputPanel.jsx, oceannavigator/frontend/src/components/FeatureSelection.jsx, oceannavigator/frontend/src/components/Layer.jsx, oceannavigator/frontend/src/components/LayerRearrange.jsx, oceannavigator/frontend/src/components/LayerSelection.jsx, oceannavigator/frontend/src/components/LayerWrap.jsx, oceannavigator/frontend/src/components/LineWindow.jsx, oceannavigator/frontend/src/components/MapToolbar.jsx, oceannavigator/frontend/src/components/ModalContainer.jsx, oceannavigator/frontend/src/components/PointWindow.jsx, oceannavigator/frontend/src/components/WarningBar.jsx, oceannavigator/frontend/src/components/time/TimePicker.jsx
Added translation tags where missing. #570
=> French translation

oceannavigator/datasetconfig.json
=> removed duplicate variable

oceannavigator/frontend/src/components/Layer.jsx
Should Fix the default dataset problem.
=> Changed default dataset ID

oceannavigator/datasetconfig.json
This is in response to a series of errors that were found by clients. Recent code and data changes have introduced instability in the calculation layer. I've fixed and removed several attributes in the config file.
All datasets except GIOPS have been disabled until we can figure out the root cause for the errors.
=> Pare down datasetconfig

routes/api_v1_0.py
Update of #624
Resolves #611 
Adds HTTP response headers to allow CORS (Cross-Origin Resource Sharing)
=> Implement CORS

oceannavigator/datasetconfig.json
we want cmems and we want it now
its the only way
no
```sh
```
=> Add CMEMS Global Monthly

oceannavigator/datasetconfig.json
=> Add CMEMS Arctic Reanalysis

oceannavigator/datasetconfig.json
Resolves #637 
Add datasets:
* GIOPS historical daily
* GIOPS historical monthly
Disable:
* Arctic Reanalysis Daily + Monthly
* Salinity variable in WCPS.
Minor tweaks to some datasets.
It's the only way
Nope
n/a
```sh
```
=> Update dataset config

scripts/generate_class4_list.py
I was notified by Dwayne that this shebang is wrong. This PR just changes it.
only way
no
no need
```sh
```
=> Change shebang

oceannavigator/frontend/index.html
Corrected the URL link to point to the correct THREDDS instance.
=> Updated the THREDDS URL.

oceannavigator/frontend/src/components/OceanNavigator.jsx, oceannavigator/frontend/src/components/WarningBar.jsx
Draw users' attention to new feature and also give heads up of where to log issues.
Only way
* Front-end will need a re-build as usual.
```sh
```
=> Add warning banner

plotting/scriptGenerator.py, plotting/templates/pythonPLOTtemplate.txt, plotting/templates/rPLOTtemplate.txt
Does not check if generated R script works though. A quick look-over shows it *should* work.
Execute a blind string substitution into the R script template so the user can download an R script.
Side note: I created an empty `__init__.py` file to resolve some import errors when running unit tests on certain environment setups.
Resulting file:
```r
library(jsonlite)
query <- '{"area":[{"innerrings":[],
"name":"",
"polygons":[[[51.289405902716794,-45.9228515625],[51.34433866059925,-53.129882812499986],[46.25584681848031,-53.48144531249999],[45.82879925192134,-46.18652343749999],[51.289405902716794,-45.9228515625]]]}],
"bathymetry":1,
"colormap":"default",
"contour":{"colormap":"default",
"hatch":0,
"legend":1,
"levels":"auto",
"variable":"none"},
"dataset":"glorys4_climatology",
"depth":0, …
```
=> Quick and dirty clean up of R script generation.

oceannavigator/frontend/index.html
Contact information update for static html landing page.
=> Changed email contact information from GMail to DFO

README.md, bin/launch-pickle.sh
Created a shell script file to index the CLASS4 datasets and updated the README.md file to provide instruction on how to update a crontab entry so that the aforementioned script is run daily at midnight.
=> Implemented a solution for automating CLASS4 datafiles

.gitmodules, README.md, oceannavigator/datasetconfig.json, oceannavigator/oceannavigator.cfg
Altering the way the oceannavigator/{datasetconfig,json,oceannavigator.cfg} files are staged depending on location. At DAL or outside of that network.
=> Altering the way the certain config files are staged

launch-web-service.sh, oceannavigator/frontend/data-help/cmems-GLOBAL_REANALYSIS_PHY_001_030.html, oceannavigator/frontend/data-help/freebiorys2v4_monthly.html, oceannavigator/frontend/data-help/giops-10day.html, oceannavigator/frontend/data-help/giops-day.html, oceannavigator/frontend/data-help/giops.html, oceannavigator/frontend/data-help/glorys12_climatology_monthly.html, oceannavigator/frontend/data-help/glorys12_climatology_seasonal.html, oceannavigator/frontend/data-help/riops.html, oceannavigator/frontend/data-help/salishseacast_2d_ssh.html, oceannavigator/frontend/data-help/salishseacast_3d_biology.html, oceannavigator/frontend/data-help/salishseacast_3d_currents.html, oceannavigator/frontend/data-help/salishseacast_3d_tracers.html, oceannavigator/frontend/data-help/wcps.html, runserver.py, runserver.sh
Adding in unique dataset help files which cut down on the help sections stored in the datasetconfig.json file.
=> Update to the information available to end users

data/netcdf_data.py, tests/test_create_app.py, tests/test_merc.py, tests/test_nemo.py, tests/test_netcdf_data.py, tests/test_variable.py
Adds more unit tests. We're now up to 183 from 177 tests.
Only way
Nope
n/a
```sh
```
=> Add more unit tests

oceannavigator/frontend/data-help/cmems-GLOBAL_ANALYSIS_FORECAST_PHY_001_024.html, oceannavigator/frontend/data-help/cmems-GLOBAL_REANALYSIS_PHY_001_030.html, oceannavigator/frontend/data-help/freebiorys2v4_monthly.html, oceannavigator/frontend/data-help/giops-10day.html, oceannavigator/frontend/data-help/giops-day.html, oceannavigator/frontend/data-help/giops.html, oceannavigator/frontend/data-help/glorys12_climatology_monthly.html, oceannavigator/frontend/data-help/glorys12_climatology_seasonal.html, oceannavigator/frontend/data-help/riops.html, oceannavigator/frontend/data-help/wcps.html
Used better HTML formatting in the various dataset files.
=> Reformatted the different dataset help files

oceannavigator/__init__.py, routes/api_v1_0.py
This is the setup required to facilitate capture and analysis of Python exceptions by Sentry. It is enabled in a container by providing an environment variable named `SENTRY_DSN` whose value is a URL generated by Sentry for the "project" on their service that is to receive the data. If the envvar is absent or empty, the Sentry integration does nothing. So, it is safe to have this code in the codebase that is used for dev or any deployment.
It's the documented way to do it: https://docs.sentry.io/platforms/python/guides/flask/
TODOs before this can go live:
[1] `blinker` (https://pythonhosted.org/blinker/) is used by the Flask signal component that `sentry-sdk` hooks into.
N/A
```sh
bash …
```
=> Add Sentry integration for backend via Flask app

.github/CODEOWNERS
By changing the .github/CODEOWNERS from Nabil to myself. I will be automatically be marked as a code reviewer for any new PRs. The person is able to select another such as James M or Doug L and deselect me from the list. But I should be notified of PRs when they are generated.
=> Changing code owner from Nabil to myself.

config/conda/navigator-spec-file.txt
Installed the zarr package from conda-forge and updated the navigator spec file. Also, I wanted to make sure that when people pull / clone the Ocean-Data-Map-Project that they get the off-site branch of the configurations repo.
=> Navigator specfile 20201210

data/calculated_parser/functions.py, plotting/colormap.py
Required for #844 
Needed this bearing calculation in another project so I figured I'd add it as a calculated variable so it can be displayed in the front-end for debugging and maybe some scientific purpose.
* Implements a bearing (degrees clockwise positive from North) calculated variable.
Copied the code in the CSV generation for bearing calculations.
Open to suggestions for colour map...https://matplotlib.org/cmocean/
```sh
```
=> Implement bearing calculated variable

config/conda/navigator-spec-file.txt
Updated gunicorn from 20.0.4 to 20.1.0 from the conda-forge channel.
=> Creation of new navigator spec file

oceannavigator/frontend/yarn.lock, plotting/scriptGenerator.py, plotting/templates/pythonCSVtemplate.txt, plotting/templates/pythonPLOTtemplate.txt, plotting/templates/rCSVtemplate.txt, plotting/templates/rPLOTtemplate.txt, tests/routes/test_api_v_1_0_generatescript.py
There isn't any template for the R CSV API script, so trying to get an R API script for CSV from the plotting window would result into an error.
I am adding a template for that case following the existing template that we have for R-Plot and it is returning a script right now. 
However I have tried to run the returned R scripts and it turns out they aren't able to download the plot or csv as they intend to do and faces error. I am looking into editing the templates so that they work perfectly.
```sh
```
=> Adding R script template for CSV download and verifying all the generated API script of Python and R are working

oceannavigator/frontend/src/components/lib/SelectBox.jsx
Fixing some linting complaints.
Longer term I want to have linting pre-commit hooks
n/a
```sh
```
=> Fix linting for SelectBox component

oceannavigator/frontend/src/components/MapToolbar.jsx
I've been seeing some error messages in the UI resulting from missing variables in console error statements such that we cannot understand why some remote requests are failing :facepalm: 
wrote log statements that make sense. sadly jquery doesn't really provide much in terms of what went wrong, so this should hold things together until I migrate these calls to `axios`.
nope
n/a
- [z] I've tested the relevant changes from a user POV.
```sh
```
=> Improve some crappy JS error messages

oceannavigator/frontend/src/components/MapToolbar.jsx, oceannavigator/frontend/src/remote/OceanNavigator.js
As the title says.
Only way
Not doing class4 this time around cuz it's doing some weird transformations.
No change to user experience:
```sh
```
=> Switch remote calls for lines, points, areas to axios

oceannavigator/frontend/src/remote/OceanNavigator.js
To be used later
Only way.
Last pr of the night
n/a
```sh
```
=> Add axios `getdepthspromise`

oceannavigator/frontend/package.json, oceannavigator/frontend/yarn.lock
Updated proj4 js package.
Only way.
Nope
No change to user experience
ARctic:
Antarctic:
```sh
```
=> Update proj4 from v2.4.3 to v2.7.5

.github/workflows/lint_python.yml, pyproject.toml
Creates a new Github Action executed on push that runs the configured `black` and `isort` tools to check Python formatting.
New check
```sh
```
=> Create Python linting workflow

README.md
=> Add lint python status badge to README

.github/workflows/python-tests.yml
=> Fix caching in github action

oceannavigator/frontend/src/components/OceanNavigator.jsx, oceannavigator/frontend/src/components/WarningBar.jsx, plotting/class4.py
**Class 4 data issues: (look below email from Greg Smith)**
Hi All,
I just had a quick look, really neat to see the observations that went in to RIOPS and how they differ from the oceanpredict class4 dataset.
Two little comments on the RIOPS dataset:
- When we click on a point to get the popup with the vertical profile the label incorrectly indicates “GIOPS”.
- There are a number of “empty” data points. For example for May 13 in the Gulf of Maine most of the points appear empty. In the pop ups for the vertical profiles, the depth ranges is very small (1-2m) and no data are shown. Is this a plotting problem or is there really no data? If it’s the latter we could perhaps filter them out on our end.
Thanks again for making this happen.
Greg
Summary of Class4 Data Issues that needs to be …
=> Class4 Data Issue Resolved- Empty Points, Plot Labels, Addition Of Banner

data/netcdf_data.py
A recent issue is preventing the Navigator from displaying the SSC 3D Currents dataset. A memory error exception is raised when requesting tiles or plotting this data. Specifically: 
`numpy.core._exceptions._ArrayMemoryError: Unable to allocate 7.31 TiB for an array with shape (140472, 40, 898, 398) and data type float32`
This error is the result of the u and v components being kept in separate datasets on the remote ERDDAP server. XArray currently does not have a built in method to lazily merge the two datasets and so tries to load the data into memory so that it can rectify coordinates before any operation. Of course, the data set is far too large and this operation results in the error above. Instead, we can instead select the u and v data separately then merge a subset of each to …
=> Manually construct SSC 3D currents dataset

oceannavigator/frontend/index.html
User notified us that open navigator button, and landing page is broken. Updated href to correct link.
```sh
```
=> Fixed change in open navigator button.

scripts/profiling_scripts/api_profiling_driver.py
Needed to update the profiling script API endpoints to work with the new API. I also took the time to properly format the scripts.
=> Update profiling scripts

plotting/scriptGenerator.py, plotting/templates/python_csv_template.txt, plotting/templates/python_plot_template.txt
python api scripts were not working
- [X ] I ran unit tests.
- [X ] I've tested the relevant changes from a user POV.
- [X ] I've formatted my Python code using `black .`.
```sh
```
=> Python api scripts fix

oceannavigator/frontend/src/components/AxisRange.jsx
upon changing variable in plot window, the value of "auto" was being ignored.
```sh
```
=> Auto selector bug

oceannavigator/frontend/src/components/DatasetSelector.jsx, oceannavigator/frontend/src/components/MapInputs.jsx, oceannavigator/frontend/src/components/OceanNavigator.jsx, oceannavigator/frontend/src/components/ScaleViewer.jsx
The share permalink button was not functioning
Defaults don't need to be accessed in DatasetSelector as they are already passed down.
```sh
```
=> Link button fix

oceannavigator/frontend/src/stylesheets/utils/bootstrap.css, oceannavigator/frontend/src/stylesheets/utils/misc.scss
#1129
Ensures that modal components are no larger than 100% of viewport
Our UI could benefit from a refresh to look cleaner in general
```sh
```
=> Modal width fix

oceannavigator/frontend/src/components/LineWindow.jsx, oceannavigator/frontend/src/components/MainMap.jsx, oceannavigator/frontend/src/components/OceanNavigator.jsx, oceannavigator/frontend/src/components/PlotImage.jsx, oceannavigator/frontend/src/stylesheets/components/_LineWindow.scss, plotting/line.py, plotting/transect.py
#1140 
Can only specify a point between the first two points of the transect.
```sh
```
=> Transect profile

oceannavigator/frontend/src/components/Map/Map.jsx, oceannavigator/frontend/src/components/Map/utils.js, plotting/map.py, utils/misc.py
Fixes #1188 
fix existing bug related to preset plots
changes made to polar projection
- [yes] I ran unit tests.
- [yes ] I've tested the relevant changes from a user POV.
- [yes] I've formatted my Python code using `black .`.
=> Predefined Area Bug Fix

plotting/basemap.py
#1193
#1201 
Area plot land resolution , shows high definition for small area and low for big area.Land data around border missing.
```sh
```
=> land data visible around 180 and resolution criteria fixed
